### ISSUE TITLE
Incompatiblity: Improved Alternate Conversation Camera

### ISSUE THREAD

**Issue by TwistedModding** [ArranzCNL/ImprovedCameraSE#1]
Improved camera seems to have a minor conflict with https://www.nexusmods.com/skyrimspecialedition/mods/68210 

Camera states are 1 & 2 with an event id of 21

Replicate: 
Increase offset values in the mcm for Improved Alternate Conversation Camera
Talk to any npc
-----------------

The camera attempts to use the offset values that are in the IACC mcm, but it gets reset to default after a short period of time

**Comment by ArranzCNL** [comment]
Shall investigate.

Was the Camera in first then switched to third as ID 21 is Third Person?

**Comment by TwistedModding** [comment]
yeah it switches to third person, and moves the camera position

**Comment by ArranzCNL** [comment]
Not a bug from Improved Camera, as system doesn't run any camera logic during those state.

Incompatibility with Smoothcam and the above mentioned mod.
