### ISSUE TITLE
Crashing at Startup

### ISSUE THREAD

**Issue by krypto5863** [ArranzCNL/ImprovedCameraSE#103]
Swapped the newest version in, it complained about my config so I just removed it. Now it gives me a black screen and quits without warning. Here's the log in case you need it.

[ImprovedCameraSE.log](https://github.com/ArranzCNL/ImprovedCameraSE/files/11003762/ImprovedCameraSE.log)

**Comment by ArranzCNL** [comment]
How have you managed to get rid of the steam overlay?

What you can do is switch to overlay mode need to edit the following in ImprovedCameraSE.ini:
iHookInput=0
iMenuMode=1

**Comment by krypto5863** [comment]
Basically, I got my game from a non-steam source. I was able to force load the steam overlay dll with MO2 and your plug worked as expected from then on. Using `iMenuMode=1` caused an odd flickering of the RivaTuner overlay though so I mostly opted `iMenuMode=0`

Just thought I'd let you know since GOG version won't have the steam overlay either if you plan to support it.

**Comment by ArranzCNL** [comment]
Rivatuner you have to make sure it uses MS Detours setting where ever it is it is a known issue with that software as OBS has issues with it.

As for GOG obviously I am aware of this.
