### ISSUE TITLE
Third Person Arms Bow without Third Person Arms Bow Aim w/ AGO

### ISSUE THREAD

**Issue by Sant90JH** [ArranzCNL/ImprovedCameraSE#106]
first person arms will flicker into view every couple seconds, making it unplayable
haven't tested it without Archery Gameplay Overhaul's meshes since I'd never play without 'em tbh
seems to work fine with the 3rdpersonBowAim enabled at the same time as BowArms but the former is too silly to aim with

**Comment by ArranzCNL** [comment]
Possibly a setting with AGO needs disabling or enabling.
