### ISSUE TITLE
ReShade is still mandatory

### ISSUE THREAD

**Issue by Acerbicon** [ArranzCNL/ImprovedCameraSE#108]
I had been considering going without ReShade for once, and upon removing it, the game won't load if ICSE is installed. Not a big deal all in all, but I just thought I'd mention it.

**Comment by ArranzCNL** [comment]
Too many external factors, general userbase should be fine. Rivatuner can be problematic if not set to MS Detours (is a known issue with OBS - streaming software) and other similar software. ReShade just fixes things so most/all hooks work as intended.
