### ISSUE TITLE
CTD on Startup

### ISSUE THREAD

**Issue by MrHildebrand** [ArranzCNL/ImprovedCameraSE#109]
Hello!

I've recently just started a fresh install of Skyrim and I've been trying to get the Improved Camera SE to work. I'm using the 1.5.97 version with SKSE 2_00_20. I also used "BestOfBoth_1.6.640.0-1.5.97.0 to downgrade my version as I have all the Anniversary edition content

Whenever I try to run SKSE, the game will appear to boot up but CTD before getting to the Bethesda logo. Upon disabling ICSE the game will launch just fine. When installing ICSE I made sure to select the 1.5.97 version in the FOMOD menu that pops up in MO2.
I have also tried disabling all other mods/plugins and get the same result.

Using Net Script Framework, or checking with SSEEdit, does not return any errors or crashes while the mod is installed.
I have attempted running Crash Logger SSE as well, but wasn't able to get it to generate a report.

In the ImprovedCameraSE.log I do find
"Failed to CreateHook for [IDXGISwapChain] Present. Error Code: (8)"
However, I am unsure of what this means, or if this is the cause of the issue.

I haven't added a lot of mods yet so my load order is pretty light. Here is a copy of my logs and load order.
https://pastebin.com/mBWTr5Gh

I apologize if there was something simple I overlooked, but any and all help is appreciated!
Thank you!

**Comment by ArranzCNL** [comment]
Do you have any other 3rd party tools running for example Rivatuner/MSI Afterburner or something? Rivatuner is known to cause issues if it is not set to MS Detours hooking.

Other than that the only thing you can do is either install ReShade to fix the issue, try with MenuMode=1, have to manually edit the ini file or completely turn it off with 0.

**Comment by MrHildebrand** [comment]
Editing the menu mode ini to 0 seemed to do the trick. Thank you! 
Do you have any kind of in depth read me file I could look at? I've only just recently came across this mod so I'm a bit out of the loop for its prerequisites.
