### ISSUE TITLE
makes game crash before beth logo

### ISSUE THREAD

**Issue by HALT77** [ArranzCNL/ImprovedCameraSE#110]
I even searched the reddit for a way to fix that...I saw something about a menu=0 or 1...but do I do that? PS: I have no other mod than SKSE, SKyui, Unnoficial patch.

**Comment by ArranzCNL** [comment]
Try MenuMode=1 but it looks like you have other external software interfering with the menu, a way around other external software causing issues is to install ReShade. I am currently not looking into how ReShade does this until ImGUI is replaced.

**Comment by Clutchboi-lad** [comment]
I've got this exact same issue, can you link the reddit post you're talking about?

**Comment by ArranzCNL** [comment]
You have a few options:
1) Install ReShade
2) Try iMenuMode=1 and turn off iHookInput=0 (ImprovedCameraSE.ini)
3) Disable the menu completely with iMenuMode=0 (ImprovedCameraSE.ini)

You only need to do one of the above.

Only reason I can think of with certain people having issues, they must have other external overlay hooks running.
