### ISSUE TITLE
Stopped working with OstimNG for some reason.

### ISSUE THREAD

**Issue by AyoubBoughaba** [ArranzCNL/ImprovedCameraSE#111]
Stopped working with OstimNG for some reason. Tried every fix there is from deactivating all mods except OstimNG and requriements and Improved camera and requirements, tried every fix there was on the OstimNG website ,
it gives me this error for some reason, if it is improved camera then its an issue , if not then sorry for bothering as im not experienced in computer stuff alot.

[Crash_2023_4_18_9-43-4.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/11259237/Crash_2023_4_18_9-43-4.txt)

**Comment by ArranzCNL** [comment]
That issue is coming from Ostim it looks like seeing OSA.dll mentioned a few times.
