### ISSUE TITLE
Game refuses to boot

### ISSUE THREAD

**Issue by PetricaT** [ArranzCNL/ImprovedCameraSE#112]
Hey, I have installed JUST this mod, literally nothing else apart from SSE Engine Fixes and it's requierment. Using the latest build form March 16 and the game works fine WITHOUT the mod. But when I turn it on, black screen for like 1-2 seconds and then a instant crash to desktop. Am I missing something?

**Comment by PetricaT** [comment]
Here is the log if it helps, all tho nothing useful seems to be in it
[ImprovedCameraSE.log](https://github.com/ArranzCNL/ImprovedCameraSE/files/11314292/ImprovedCameraSE.log)

No overlays are being used (Afterburner / Discord)

**Comment by PetricaT** [comment]
nvm i'll just fiddle with it more, i see a lot of people are having this issue too

**Comment by ArranzCNL** [comment]
It is not a lot of people it is just a random event occuring on certain PC setups for some odd reason and it has to be some external factor I am unaware of running in the background screwing with the hook. I'll be looking at it more intently once the initial NG release is out of the way as I need to anyhow!

All you can do for now is use iMenuMode=1 or iMenuMode=0

**Comment by PetricaT** [comment]
I would like to confirm that MenuMode=0 has worked (1 did not)

**Comment by ArranzCNL** [comment]
That basically confirms one of two things either Skyrim is inside of a protected folder or another app you have running in the background is doing DX11 hooking and screwing things up. As iMenuMode=1 it should be ignored. I know discord doesn't ignore it and injects itself into that window without doing a re-check what it is injecting into!

I'll have to do some research how to block other apps hooking it.
