### ISSUE TITLE
Crashing To Deskstop - Have no clue why (MO and New Profile)

### ISSUE THREAD

**Issue by TopherChristian777** [ArranzCNL/ImprovedCameraSE#113]
Game Version Skyrim SE 1.597 and Loot says I am using the correct version of SKSE for this 
Steam Version 
1. Using MO 
2. Launching game MO using SKSE I had no CTDs prior to installing most updated 
3. Created a new profile installed mod checked box to activate
4. Launched game same way as before and game would CTD 
5 Have no clue why it is crashing to desktop 

Below is current Modlist I am using on for this profile thanks for anyone help you can give me 
TOpher 
# This file was automatically generated by Mod Organizer.
-Skyrim Wayshrines - Immersive Fast Travel - SWIFT SE
-Smooches of Skyrim
-Proudspire Manor TNF Beds Plus
-Improved Camera
-OWintersun
-OVirginity Reflowered
-ORomance Plus
-ORomance
-OCum Ascended
-OComfort - OStim Lovers Comfort
-Fertility Mode v3 Fixes and Tweaks
-Fertility Mode - Additional Scents
-Fertility Mode
-Fertility Adventures
-Breezehome TNF Beds Plus
+Wintersun - Book Covers Skyrim Patch
+Landscape Fixes For Grass Mods - CRF and Alternate Start Patches
+Landscape Fixes For Grass Mods - Immersive Citizens
+Realistic Boat Bobbing - USSEP Patch
+Maybe Not That Useless Patches Collection
+kryptopyr's Automated Patches
+Nemesis Test
+Project New Reign - Nemesis Unlimited Behavior Engine
+Project New Reign - Nemesis PCEA
+Wonders of Weather
+Storm Lightning for SSE and VR (Minty Lightning 2019)
+Relighting Skyrim SE
+Luminosity Lighting Overhaul - The Cathedral Concept
+Cathedral Weathers and Seasons
+Cathedral Weathers MCM
+Smooth Shores (Grass and Ground Remastered)
+Oblivion Gates Remade
+Landscape Fixes For Grass Mods
+Bring Out Your Dead
+Skyrim Skill Uncapper
+Hearthfire multiple adoptions - Now with custom home support for kids and spouse
+Lock Overhaul
+The Paarthurnax Dilemma
+Timing is Everything SE
+Thieves Guild Requirements SE
+The Choice is Yours
+Not So Fast - Main Quest
+Here We Go Again - World Interactions
+Gildergreen Regrown
+PapyrusUtil SE - Modders Scripting Utility Functions
+Improved Camera OStim configuration
+Improved Camera SE
+OPrivacy
+Open Animations Romance and Erotica (former OpenSex)
+OStim NG - OSA Overhaul and API Next Gen
+OSA.for.OStim.1.3
+Customizable Companions Questline Progression Requirements
+Even Better Quest Objectives SE
+Alternate Start - Live Another Life - SSE
+Andromeda - Unique Standing Stones of Skyrim
+Wintersun - Faiths of Skyrim
+Simple Drop Lit Torches SE
+Torches Ignite Oil
+RDO - CRF and USSEP Patches Final
+Relationship Dialogue Overhaul - RDO SE
+Reasonable Movement Speed
+Nether's Follower Framework
+Point The Way
+Get Snowy
+Campfire 1.12.1 and Frostall 3.4.1SE - Unofficial SSE Widescreen Fix
+Campfire and Frostfall - Unofficial SSE Update
+Frostfall - Hypothermia Camping Survival
+Wet and Cold SE
+Improved Traps
+Guard Dialogue Overhaul SE
+Disease Descriptions for the Immersive Adventurer
+Convenient Horses Special Edition Patch
+Convenient Horses
+Butterflies Unchained (ESL Version) - Complete Alchemy and Cooking Overhaul Patch
+Butterflies Unchained
+Ecotone Dual Sheath
+Mysticism - Ordinator Patch
+Mysticism - A Magic Overhaul
+Apocalypse - Ordinator Compatibility Patch
+Apocalypse - Magic of Skyrim
+Trade and Barter
+Unequip Quiver SE
+Tavern AI fix
+Run For Your Lives
+Imperious - Races of Skyrim
+Immersive Citizens - AI Overhaul
+Weapons Armor Clothing and Clutter Fixes
+GIST - Genuinely Intelligent Soul Trap SE
+Complete Crafting Overhaul Remastered
+Complete Alchemy & Cooking Overhaul
+Waterbreathing Breathless Emerge SSE
+Unlimited Bookshelves
+Skyrim Project Optimization SE
+NPC AI Process Position Fix - NG
+Invisibility and Eyes Mesh Fix by HHaleyy
+Eye Normal Map Fix SSE
+Butterflies Land True
+Critters Ain't Snitches - Animal and Monster Crime Reporting Fix
+Enchantment Reload Fix SE
+BodySlide and Outfit Studio
+Vanilla Warpaints Absolution
+VMHD - FemaleLowerEyeSocketFix - 2K
+Vanilla Makeup HD - HD Racial Colors and Makeup for all Races and Genders - SE
+TK Children
+Weapons Armor Clothing and Clutter Fixes - CBBE Patch
+Bijin AIO SE for USSEP
+Bijin NPCs SE
+Bijin Warmaidens SE
+Bijin Wives SE
+Tempered Skins for Males - SOS Full Version
+Tempered Skins for Females CBBE
+Schlongs of Skyrim SE
+Caliente's Beautiful Bodies Enhancer -CBBE-
+Superior Lore-Friendly Hair - HD textures
+Simple Children
+Northborn Scars
+Natural Eyes
+More Realistic Hair
+Female Vampires Have Fangs
+Terre's 4K Fur Textures for CoverKhajiits
+Digitigrade Beast Races for Skyrim SE
+CoverKhajiits - Face Textures 4K SE
+Consistent Older People
+Hvergelmir's Aesthetics - Brows
+Hvergelmir's Aesthetics - Beards
+Winter Is Coming SSE - Cloaks
+Wispmother.by.Kajuan
+Whiterun Trellis Redesigned SE
+White Phial Replacer SE
+WEBS S.E
+Ultimate HD Torch
+Troll.by.Kajuan
+Dawnguard Rewritten - Arvak
+Sweet Mother - the Night Mother Improvement
+Superior Mudcrab 2K1K - Creatures
+Superior Mudcrab - 4k Retexture
+Stalhrim Source
+SSIRT v4.1
+SABRECAT.by.Kajuan
+RUSTIC WINDOWS - Special Edition
+RUSTIC SOUL GEMS
+RUSTIC FROSTBITE SPIDER - Special Edition
+RUSTIC ELDERSCROLL - Special Edition
+RUSTIC DRAGONS - Special Edition
+RUSTIC DRAGON CORPSE - Special Edition
+RUSTIC DEATH HOUND and GARGOYLE - Special Edition
+RUSTIC DAEDRA - Special Edition
+RUSTIC COOKING - Special Edition
+RUSTIC AZURA'S STAR - Special Edition
+RUSTIC AMULETS - Special Edition
+Ren's HD Shrines by Rengel
+Remove Small Rocks
+Realistic Water Two SE
+Rally's Instruments HQ
+Rally's Hooks and Saws
+Rally's Hanging Moss
+Pilgrims Delight - High Hrothgar Shrine Retextures
+N-R HD Display Case
+Northfire's Skidmarks SE ADDONS
+Northfire's Skidmarks SE 2K-4K
+Metallurgy - Ingots Ore and Veins HD
+Mammoth.by.Kajuan
+LeanWolf's Improved Enchanter Candle Meshes SE
+LeanWolf's Better-Shaped Weapons - All in One Installer
+Inferno - Fire Effects Redux
+Improved Sparks -Impact Effects - Vanilla Sparks
+Improved Sparks -Grindstone -Vanilla Sparks
+Improved closefaced helmets
+Immersive Smilodons
+High-Res Dartwing (Dragonfly) Texture
+HD Road Signs 2K Version
+HD Dark brotherhood door - No glowing eyes version
+HD Dark brotherhood door
+HD Reworked Horses
+Hagraven.by.Kajuan
+Giant.by.Kajuan
+Footprints
+ETHEREAL CLOUDS - Special Edition
+Enhanced Blood Textures
+Embers HD
+ElSopa HD - Briar Heart
+Deathbell HD - All-New Textures (2K-1K)
+Deadly Spell Impacts
+Dark Brotherhood Tenets Restored - Performance Edition
+Book Covers Skyrim - Lost Library
+Book Covers Skyrim
+Better Dynamic Snow SE
+Better Dynamic Ash SE
+Bellyaches Animal and Creature Pack
+Barenziah's Glory SE
+Frankly HD Stormcloak and City Guards -SpritterSan 2k Fix
+Frankly HD Stormcloak and City Guards -Falkreath Matched Color Fix
+Frankly HD Stormcloak and City Guards
+Armor Mesh Fixes SE -aMidainBorn Blades Helmet Patch
+Armor Mesh Fixes SE -Steel Armor Fix
+Armor Mesh Fixes SE
+Remiros' Chitin Armor HD
+Remiros' Ancient Falmer Armor HD
+CC's UHD Stalhrim Weapons and Armor
+JS Helm of Yngol SE
+Frankly HD Nightingale LeanWolfs Better-Shaped Weapons and Dual Sheath Redux Patch
+Frankly HD Nightingale Armor CBBE SE
+Frankly HD Nightingale Armor and Weapons [SSE]
+Frankly HD Thieves Guild Armors
+Frankly HD Miraak HOTFIX 1.11
+Frankly HD Miraak [SSE]
+Frankly HD Masque of Clavicus Vile
+Frankly HD Imperial Armor And Weapons - Sleeves and Pants Edition
+Frankly HD Imperial Armor And Weapons - Leanwolf Better Shaped Weapons Patch
+Frankly HD Imperial Armor and Weapons
+Frankly HD Dragonbone and Dragonscale - Mesh patch
+Frankly HD Dragonbone and Dragonscale - Armor and Weapons
+Frankly HD Dawnguard Armor CBBE SE
+Frankly HD Dawnguard Armor and Weapons
+Armor and Clothing Extension
+aMidianBorn stormcloak officer armour
+aMidianBorn Content Addon
+aMidianBorn Book of Silence SE
+Campfire - Complete Camping System (Supports Skyrim VR)
+JK's Skyhaven forge
+CC's Castle Volkihar Remastered
+Blue Palace Roof Mesh Fix
+XP32 Maximum Skeleton Special Extended
+Stronger Swimming Animation SE
+Run Sprint and Jump (Special Edition)
+RBB - SMIM Meshes
+Realistic Boat Bobbing SE
+Dual Wield Improved Animation SSE
+D13 Faster GET UP STAND UP animation vanilla friendly SSE
+Skyrim Fixes Collection
+HD LODs Textures SE
+SavrenX Solstheim Creatures
+RUSTIC RELIEFS
+RUSTIC CLUTTER COLLECTION - Special Edition
+RUSTIC CLOTHING - Special Edition
+RUSTIC ARMOR and WEAPONS SE
+Landscapes - Cathedral Concept
+Riften in High Definition
+Prisoner cart fix SMIM
+NSM - SMIM Patch
+B. Noble Skyrim - FULL PACK_Performance Edition
+Cathedral - Plants
+Assorted mesh fixes
+Skyrim Landscape and Water Fixes
+SMIM - Noble Skyrim Patch
+Misc. SMIM Fixes
+Static Mesh improvement Mod - SMIM - Quality Addon
+Static Mesh Improvement Mod
+Project Clarity AIO - Skyrim Textures Redone
+Cleaned Skyrim SE Textures
+iWant Widgets
+UIExtensions
+Wider MCM Menu for SkyUI
+Stay At The System Page NG
+Sovngarde - A Nordic Font
+SkyUI Item Card Fixes
+Skyrim Souls RE - Updated
+Smaller Vanilla Cursors
+Remove QuickSave and Help Buttons
+Regional Save Names
+RaceMenu - Male Khajiit Mouth Expression Fix
+RaceMenu
+More Informative Console
+Lore-Based Loading Screens
+Jaxonz MCM Kicker SE
+Hide Your Quests (ESL flagged)
+Guard Dialogue Overhaul MCM
+ConsolePlusPlus
+Complete Widescreen Fix -Flashing Savegames Fix
+Complete Widescreen Fix -Better Message Box Control
+Complete Widescreen Fix -Better Dialogue Control
+Complete Widescreen Fix for SkyUI 5.2 SE Alpha - 2560x1080
+Better MessageBox Controls
+Better Dialogue Controls
+Start On Save
+Whose Quest is it Anyway NG
+Main Menu Spinning Skyrim Emblem
+Clean Menu Plus
+Immersive HUD - iHUD Special Edition
+moreHUD SE
+moreHUD Inventory Edition
+Extended Hotkey System
+Relationship Change Notifications
+Hunters Not Bandits
+Ghosts Mechanics and Shaders Restored - Cut Content Restoration
+Cutting_Room_Floor
+No Vampire Sun Damage in Soul Cairn - Apocrypha - etc
+Hearthfires Houses Building Fix
+HearthFires Display Case Fix SE
+Fuz Ro D-oh - Silent Voice
+Enhanced Invisibility
+Charge Dialogue Fix
+WIDeadBodyCleanupScript Crash Fix
+Unofficial Skyrim Special Edition Patch
+Unofficial High Definition Audio Project - Voices Part 2
+Unofficial High Definition Audio Project - Voices Part 1
+Unofficial High Definition Audio Project
+JContainers SE
+MCM Helper
+SSE Fixes
+Skyrim Priority SE AE - skse plugin
+SSE Engine Fixes (skse64 plugin)
+SSE Display Tweaks
+Shadow Boost
+Archery Quick Shot Perk Bug Fix
+PrivateProfileRedirector SE - Faster game start (INI file cacher)
+Particle Patch for ENB
+No more Radial Blur - Performance optimization
+MfgFix MCM
+Mfg Fix
+1st Person Candlelight Fix
+Homecooked Meal Bug Fix
+Fix Note icon for SkyUI (SKSE64 plugin)
+First Person Sneak Strafe-Walk Stutter Fix
+Face Discoloration Fix
+Equip Enchantment Fix
+Chillwind Depths CTD Fix
+Bug Fixes SSE
+Actor Limit Fix
+Ordinator - 50 percent More Perk Points
+Ordinator - Perks of Skyrim
+NL_MCM - A Modular MCM Framework
+Spell Perk Item Distributor
+SkyUILib
+SkyUI
+Scaleform Translation Plus Plus NG
+powerofthree's Papyrus Extender
+powerofthree's Tweaks
+ConsoleUtilSSE NG
+.NET Script Framework
+FileAccess Interface for Skyrim SE Scripts - FISSES
+Address Library for SKSE Plugins
*DLC: Dawnguard
*DLC: Dragonborn
*DLC: HearthFires

**Comment by TopherChristian777** [comment]
i installed Reshade and I was able to load the game and it didn't CTD hope that fixes it

**Comment by ArranzCNL** [comment]
You must have another external overlay running on your system, will be looked into again after initial NG release to see if there is anything I can do about it. Basically a dummy swapchain is created and these other external overlays hook it (hence the crash), steam doesn't since PR5 as I hook steam instead :D
