### ISSUE TITLE
MO2 can't install this mod?

### ISSUE THREAD

**Issue by GSSubmarine** [ArranzCNL/ImprovedCameraSE#114]
![Capture1](https://user-images.githubusercontent.com/132408116/236065720-2aa5c7b3-14cc-4fa3-a9af-4fc98f858ec6.JPG)

Whenever I add this zip to MO2, it brings up this error message. I dug around for a read me, only to find the one in the zip contains no information.

Am I installing this wrong?

**Comment by Kruziikrel13** [comment]
Yes you are installing this wrong. Right click on ImprovedCameraSE-main and select 'Set as data directory'

This is a very very basic task and should be one of the very first things you learn to do upon installing MO2. Alternatively you should be able to recognise what the contents of a data directory comprise of.

**Comment by ArranzCNL** [comment]
It looks like you have downloaded the wrong file.
[https://github.com/ArranzCNL/ImprovedCameraSE/releases](https://github.com/ArranzCNL/ImprovedCameraSE/releases)

Make sure to click assets at the bottom of the page and it is the top file from that.

**Comment by GSSubmarine** [comment]
> It looks like you have downloaded the wrong file. https://github.com/ArranzCNL/ImprovedCameraSE/releases
> 
> Make sure to click assets at the bottom of the page and it is the top file from that.

Thank you very much for the aid. I have been modding for 12 years now, and only just recently switched to MO2, still trying to get the program down. 

Thank you for your patience with me. This mod has always been one of my favorites and it just isn't Skyrim without it, and I was trying very hard to figure out the issue on my own before posting here.

**Comment by Kruziikrel13** [comment]
Haha teach me to eat my words, Sorry I gave you bad info. Also been modding around 12 years and saw this issue and thought I had it figured out at a first glance.
