### ISSUE TITLE
having seizure on mod Precision

### ISSUE THREAD

**Issue by asanew90** [ArranzCNL/ImprovedCameraSE#115]
when walking backward on first person while weapon drawn the body having 1 sec delay while Precision mod is on, and 1 sec lag when weapon attack.

**Comment by ArranzCNL** [comment]
Need more info as never witnessed that happen, I know there are issues with a certain combat mod (can't remember the name of it now) but that is out of my hands as IC is dependant of certain game triggers to occur.
