### ISSUE TITLE
Problems with Immersive Interactions 1.67 & Improved Camera PR5 - Skyrim AE 1.6.353

### ISSUE THREAD

**Issue by Painbringer07** [ArranzCNL/ImprovedCameraSE#117]
I have Improved Camera PR5 and Immersive Interactions 1.67 installed together.  When interacting with Locks, Standing Stones, and a couple of doors, I am teleported back to the last cell I loaded in from.  From what I have seen, setting Immersive Interactions to "Force 3rd Person" in the MCM is the accepted fix for this. Just wondering if there are any alternatives.

Thanks.

**Comment by asanew90** [comment]
is there a chance you install "Save Unbaker" on your exist save file? cus thats whats happening to me before when i install it on mid game, when i enter to other door "ex dragonreach" sometimes i go back to my homestead house, if so its better to create a new game cus the scripts got separated.

**Comment by Painbringer07** [comment]
> is there a chance you install "Save Unbaker" on your exist save file? cus thats whats happening to me before when i install it on mid game, when i enter to other door "ex dragonreach" sometimes i go back to my homestead house, if so its better to create a new game cus the scripts got separated.

Yes, I do have Save Unbaker installed. But I have since created a new game many times over already (updating other mods).
As I understand it, the teleporting happens when the game tries to play 3rd person animations while you are in 1st person mode.
The author of Immersive Interactions suggests to use Immersive First Person View, but that mod is not available for AE users.
I may just end up changing the MCM settings like others have suggested.

Thank you for your thoughts though.

**Comment by ArranzCNL** [comment]
Third Person is the recommended setting.

Most animations from mod authors and even the vanilla game itself cannot play these animations in first person as it causes issues as describe. The option Jayserpa added for First Person is no doubt a compatibility thing as IFPV works completely differently.
