### ISSUE TITLE
Read The Room - Forced first person

### ISSUE THREAD

**Issue by xMizta** [ArranzCNL/ImprovedCameraSE#119]
The equip/unequip animations from the mod Read The Room forces first person whilst the scripted event is toggled.
The strange issue that it didn't start that way but started after a few hours of playtime. Initially you stay in third person if the animation is activated from third person.
Has happened to me on two different saves without updating either mod.
I realize turn off for scripted events but then I might miss functionality for other mods.

**Comment by ArranzCNL** [comment]
This happens if you are the closest zoom level in third person, if you zoom out by one click it will play in third person instead. I haven't found a suitable solution to this as of yet, although on my radar.
