### ISSUE TITLE
SSE Display Tweaks Incompatibility

### ISSUE THREAD

**Issue by terravox** [ArranzCNL/ImprovedCameraSE#12]
When BorderlessUpscale enabled my cursor selection does not match what is being highlighted in this mods in-game menu. I believe its because I have my games resolution set lower than what my screen is. When disabling BorderlessUpsacle the game window is small but the selection problem doesn't happen.

**Comment by ArranzCNL** [comment]
Sounds like a dpi issue, shall look into it.

Thanks for the report.

**Comment by ArranzCNL** [comment]
Do you know if DisableBufferResizing=true fixes your issue?
