### ISSUE TITLE
Random Mouse Clicks result in alt-tab behavior on windows

### ISSUE THREAD

**Issue by vernonator63** [ArranzCNL/ImprovedCameraSE#121]
At random time clicking with the mouse in any form (attack, menu selection, map navigation, etc) results in an alt-tab like action. View switches to any other open applications. This is occuring on Windows 10 and Skyrim SE 1.5.97.0. Using MO2 to install DLL.

**Comment by vernonator63** [comment]
Update - installed directly rather than via MO2 and issue still present.

**Comment by ArranzCNL** [comment]
I assume this is PR5, you should be able to click on another window then alt+tab back to Skyrim it should be fixed. Unless something else is inteferring with it.

**Comment by vernonator63** [comment]
Yes this is PR5, and yes I can alt+tab back, but it continues to occur (it is not a 1 time event). This started when I added PR5 and stops when I remove it.

**Comment by ArranzCNL** [comment]
Only thing you can do is set it to MenuMode=1 or switch it to 0 (ImprovedCameraSE.ini)

**Comment by vernonator63** [comment]
Did not work - set to 1 or 0. Is there a location to get the previous version?

**Comment by ArranzCNL** [comment]
Then it is coming from something else or your not on PR5-Hotfix 3 or Beta6 (from discord).

As that whole system is completely shutoff with MenuMode 1 or 0 to do with input.

**Comment by ArranzCNL** [comment]
I apologise I retroactively applied an additional fix to PR5-hotfix3 which didn't make it public however Beta6 which is available on discord should fix the issue.
