### ISSUE TITLE
Xbox port

### ISSUE THREAD

**Issue by seadx6-neo** [ArranzCNL/ImprovedCameraSE#124]
Hello everyone who is involved in this mod, could be possible some day to port this mod for Xbox? Or you think it would be impossible due to the many scripts PC mods have? Would at least a light version be possible?

**Comment by ArranzCNL** [comment]
How does Joy of Perspective work on Xbox, if at all?

I'll try to remember looking back here as the NG version is the more up to date and official.

**Comment by ArranzCNL** [comment]
To do it a bit more successfully it is not possible unfortunately due to papyrus missing vital functionality which Skyrim Script Extender adds.
