### ISSUE TITLE
Signature not found when combined with other mods

### ISSUE THREAD

**Issue by Lucyous** [ArranzCNL/ImprovedCameraSE#15]
I've been getting a DLL error pop-up when trying to add this mod and launch through MO2.

![image](https://user-images.githubusercontent.com/108126957/175515694-a47fadb9-c760-47fb-8095-3c12d82f7388.png)

I've checked that SKSE is definitely working correctly and it's the latest version for SSE.

The other SKSE mods with DLL I have are:
Campfire
Take Notes - Journal of the Dragonborn SSE
RaceMenu
SSE Engine Fixes
PapyrusUtil SE
Dynamic Animation Replacer
DynDOLOD

I've been using the old beta version which has been working fine.

**Comment by ArranzCNL** [comment]
**Edit:**
Do you have any .NET mods installed?

Nice thank you, I do already have an issue for this one but can't trace it for the other user as they have a massive list which I still need to slowly go through.

I checked out the others I don't have, Campfire you need to remove the dll anyhow and the other 2 don't seem to have SKSE dlls.

I am suspecting RaceMenu somehow.

I shall work on a fix and drop a test version in here after I've had lunch.

**Comment by ArranzCNL** [comment]
Can you please test this version, I xref the address instead now.

Any addition popups like that report in here, so I can clean sweep them all.

**Comment by Lucyous** [comment]
That works perfectly now - no errors popping up! 
I also don't have any .NET mods installed.

Thank you for helping!

**Comment by ArranzCNL** [comment]
Still odd what the issue was but least it is resolved now and thanks for testing the fix!

I'll keep this open until I either stealth update PR2 or maybe do PR3.

**Comment by ArranzCNL** [comment]
Stealth update applied.
