### ISSUE TITLE
Feature Request: Allow loading of different camera ini profiles through either keybinds or papyrus interface

### ISSUE THREAD

**Issue by Arial6502** [ArranzCNL/ImprovedCameraSE#17]
I have personaly hacked beta 4 together to be able to switch between 2 ini files uppon a keypress. It would be great if this functionality was implemented as a propper feature in this version through either a configurable key or a papyrus interface.

**Comment by ArranzCNL** [comment]
Json is planned for v1.2.0 for profiles etc as it gives more flexibility to work with, although mINI shall still be kept around for just the [MODULE DATA] section.

Cannot obviously give a timeframe or anything since v1.0.1 isn't even released yet.

**Comment by ArranzCNL** [comment]
Closing as planned feature for 1.2.0, maybe sooner.
