### ISSUE TITLE
Stuck in craft animation

### ISSUE THREAD

**Issue by kahel98** [ArranzCNL/ImprovedCameraSE#19]
Sometimes, not aways, but sometimes the crafting menu doesnt shows and i cant leave the crafting, so i have to reload.

**Comment by TwistedModding** [comment]
Does it happen without this mod enabled? If so provide steps to reproduce, i havent run into this issue yet and i craft stuff fairly often.

**Comment by ArranzCNL** [comment]
As TwistedModding mentioned and expanding upon it this seems very suspicious another mod is interferring or actually causing the issue. Use a different technique compared to previous versions for picking up/releasing on crafting which is pretty much failsafe.
