### ISSUE TITLE
Water turning opaque when looking down in first-person

### ISSUE THREAD

**Issue by fadingsignal** [ArranzCNL/ImprovedCameraSE#2]
**DESCRIPTION**

When standing near a body of water and looking down in first person, the water will turn solid/opaque.  This can be reproduced at any body of water.

Disabling the DLL resolves the issue.

**STEPS TO REPRODUCE**

- Enable DLL
- Load the game
- COC POINorthernCoast01
- Run up to the ocean edge
- In first person, look down far enough to see your own body
- Notice the water turns opaque
- Disable plugin and reload game, observe issue no longer happens
- Enable plugin and reload game, issue continues

**IMAGES**

![SkyrimSE 2022-06-18 21-05-33](https://user-images.githubusercontent.com/13229928/174465574-afa8de31-8d1e-41c0-8c36-dd0cc2a6dff0.jpg)
![SkyrimSE 2022-06-18 21-05-38](https://user-images.githubusercontent.com/13229928/174465575-83bdc168-46f4-43d6-abf1-eeafd40761f6.jpg)
![SkyrimSE 2022-06-18 21-07-58](https://user-images.githubusercontent.com/13229928/174465577-15f638f5-2436-4342-bc39-b82c68e94210.jpg)
![SkyrimSE 2022-06-18 21-08-01](https://user-images.githubusercontent.com/13229928/174465578-fb11ad2c-4d1f-45d7-b257-f99676494617.jpg)
*

**Comment by fadingsignal** [comment]
I wonder if there's some sort of engine culling going amok here.

**Comment by ArranzCNL** [comment]
It was the only way to solve seeing your body without clipping when looking downwards.

Under the Near Distance menu:
You can change the Pitch Threshold and or increase the First Person 4.0 (default) to something higher 15 is game default however you will start seeing through your body slightly.

I just tried finding a happy balance.


It is something I do want to investigate further as First Person skeleton seems completely unaffected by neardistance, so I imagine a flag must be set on the Third Person skeleton. As soon as that is found Near Distance can be completely removed!

I will keep this live but as it stands it is just a limitation currently.

**Comment by fadingsignal** [comment]
Sounds good, just wanted to report it, thank you for your hard work on this!  It's fantastic!

**Comment by ArranzCNL** [comment]
Going to close this and create an enhancement post based upon this.
