### ISSUE TITLE
Incompatibility with Misc High Heels Sitting Height Fix

### ISSUE THREAD

**Issue by Sermitse** [ArranzCNL/ImprovedCameraSE#20]
Upon loading a save it throws this error "**Signature with search_start=3db420 not found! Module that caused this error: ImprovedCameraSE.dll**"
If activated through Mod Organizer 2, it throws this same error before game is launched, not even reaching Bethesda menu
Not sure which exact plugin creates this error, i'll try to disable them one by one in hope to find conflicting plugin
![SkyrimSE_5Fbl41kFmE](https://user-images.githubusercontent.com/108320865/177014817-f94d4e3b-0868-415d-871d-58dc9752a14f.png)

Edit: seems to be an incompatibility with Misc High Heels Sitting Height Fix, removing its DLL fixed it

**Comment by ArranzCNL** [comment]
Ok that is rather weird, why would it be using: ApplyMasksToRenderTarget

Thanks for the report shall install that mod and work on a fix.

**Comment by Sermitse** [comment]
Thank you, hoping for a fix, also forgot to mention that this error was before i figured out the conflicting mod

Error with Misc High Heel Setting Height Fix is the following: 
![SkyrimSE_vOo5ZZQXQj](https://user-images.githubusercontent.com/108320865/177016900-bfa0119e-e127-4b0f-b226-992b61ae0139.png)

**Comment by ArranzCNL** [comment]
Although I might be able to fix that error for High Heels there is no guarantees it will still work, since the author is AWOL and not released the source. Least I know where that error is coming from now for UpdateNode, as whoever reported it on reddit didn't list their skse mods.

Where did the first error come from?

**Comment by Sermitse** [comment]
Honestly no idea where that first error came from, i had my suspicions towards Skyrim Platform but now it loads fine with v2.5.0 and 2.6.0, so i have no idea what was causing it: as soon as i removed High Heel DLL, errors went away

**Comment by Hansukie** [comment]
This is a different version of high heel fix and the author is active:

[https://www.nexusmods.com/skyrimspecialedition/mods/64442?tab=description](https://www.nexusmods.com/skyrimspecialedition/mods/64442?tab=description)

Perhaps this one will give no error.

**Comment by ArranzCNL** [comment]
> This is a different version of high heel fix and the author is active:
> 
> https://www.nexusmods.com/skyrimspecialedition/mods/64442?tab=description
> 
> Perhaps this one will give no error.

I see that one is a non-dll so yeah that'll work fine. I'll still do a fix for that address just in case.

**Comment by ArranzCNL** [comment]
Closing as [Heels Fix](https://www.nexusmods.com/skyrimspecialedition/mods/64442?tab=description) is a better replacement.

**Comment by ArranzCNL** [comment]
Update: Misc High Heels Sitting Height Fix was not the issue as just tested it.
