### ISSUE TITLE
shadow scene node crashing

### ISSUE THREAD

**Issue by zhongjiedong** [ArranzCNL/ImprovedCameraSE#21]
[Crash_2022_7_4_16-21-49.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9040660/Crash_2022_7_4_16-21-49.txt)

This was supposedly fixed by engine fixes a while ago but ever since installing PR2 I've been getting these in random places again. One was windhelm marketplace, another in the LotD museum in the relic preparation room and now in the college hall of attainment.

It's always the same type of crash, names a mesh inside  nif and then shadow scene node. I'll try playing for a while without improved camera to get some more conclusive data.

**Comment by ArranzCNL** [comment]
Looks like an issue with:
Nordic Ruins of Skyrim.esp

However speaking from limited experience Lux can also cause this if the loadorder for it is out of whack, as when I started testing with a modded game around Riverwood which was working fine then did a new game with LAL I kept instantly CTD when moving. Initially yes it was experimental hooks from Improved Camera (which none of the PR's have at all). Still happened after not having it running then figured out Lux was the last thing I installed and didn't have the loadorder of it setup correctly.

There is even no mention of Improved Camera throughtout other than it is loaded.

**Comment by zhongjiedong** [comment]
I doubt it's the nordic ruins, as I said this also happened inside Windhelm and inside the LotD museum even. Nordic ruins also only uses vanilla assets.

 Windhelm even had a vanilla mesh as the possible releva
[Crash_2022_7_4_12-41-7.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9041222/Crash_2022_7_4_12-41-7.txt)
nt objects so I don't think it's Lux meshes crashing either.

**Comment by ArranzCNL** [comment]
Either way nothing points to improve camera it is not even in the stack trace for either log report. Looks like you have possibly multiple issues with your mods.

From both of your reports:
1. BSTriShape(Name: `WinterholdSBTowerIntStairs01:1.001`)
2. BSMultiIndexTriShape(Name: `WHdockdoortrim:68`)

**Comment by zhongjiedong** [comment]
as I said, the second mesh is vanilla, there's nothing touching that at all. First one is a Lux mesh

**Comment by ArranzCNL** [comment]
Closing this as getting nowhere.
