### ISSUE TITLE
Spontaneous switching form 3rd to 1st person during certain animations

### ISSUE THREAD

**Issue by yytelliot** [ArranzCNL/ImprovedCameraSE#23]
Some animations such as sitting down at a table or crouch sliding (https://www.nexusmods.com/skyrimspecialedition/mods/39157) cause the camera to switch to first person view for the duration of the animation if the camera is too close to the character in third person view. This does not happen when the camera is zoomed further out when performing these animations.

**Comment by ArranzCNL** [comment]
That is intended behaviour with third party mods depending on the event they are categorized in. If your at the closest zoom level and they trigger scripted for example it'll play out in fake first person, one click back it should remain in third person.

As for sitting down that is unintended bug, I think I finally tracked down and fixed last night, need to run more tests on it. As you could sit down in third person fine for the first time but try for the second time it'll put you into first person view.

I shall try out that mod though looks like a fun one to play around with!

**Comment by ArranzCNL** [comment]
Thats a cool mod but yep maybe one click away from first person this triggers the fake third person, need to be 2 clicks out.
