### ISSUE TITLE
Game freezes/crashes when using SOS Female Pubic Hairs colored with IC-PR3 installed

### ISSUE THREAD

**Issue by NaturalGasss** [ArranzCNL/ImprovedCameraSE#24]
This issue is very specific and esoteric so feel free not to respond if you're not comfortable.

There is an issue when using IC-PR3 and SOS Female Pubic colored for NPCs, more specifically the auto-color changing of pubic hairs

To reproduce this, a few mods are required:
1) Racemenu SE- https://www.nexusmods.com/skyrimspecialedition/mods/19080
2) Schlongs of Skyrim SE - https://www.loverslab.com/files/file/5355-schlongs-of-skyrim-se/
3) PapyrusUtil SE - https://www.nexusmods.com/skyrimspecialedition/mods/13048?tab=description
4) SOS Female Pubic Hairs colored for NPCs 2.0.4 - https://www.loverslab.com/files/file/10318-sos-female-pubic-hairs-colored-for-npcs/
5) Any nude body replacer

Process for reproducing:
1) In game, spawn any female NPC
2) Ensure that in the SOS mod menu they have pubic hair equipped (should be automatically equipped already)
3) remove all their equipment, the game should freeze
4) The game also freezes to a black screen when loading savegames with any NPCs that are naked with the pubic hair equipped

I did a lot of testing and discovered that:
1) Removing PHFPubicHairs.xml from SKSE\Plugins\NiOverride\TintData\Armor fixes the issue but the auto-color changing function is disabled
2) Removing the pubic hair mesh fixes the issue
3) Removing skee.dll from RaceMenu fixes the issue
4) Disabling IC-PR3 fixes the issue

There seems to be some conflict between the auto-color changing fuction of Pubic Hairs and your mod.

Anyway this issue happens only after I've installed IC-PR3. Super strange that it conflicts with a pubic hair mod of all things lol

**Comment by ArranzCNL** [comment]
Wth that is a weird bug!!!

**Comment by ArranzCNL** [comment]
Unable to reproduce the hair is changing as should with no freezing/crashing issues. (Although this is tested on the about to be released PR4!)

Since your on SE maybe you don't have installed [RaceMenu 0.4.16 Memory Leak Hotfix (SE)](https://www.nexusmods.com/skyrimspecialedition/mods/70161?tab=description)?

**Comment by NaturalGasss** [comment]
Thanks for troubleshooting, guess I'll have to test it out again with the new release then!
