### ISSUE TITLE
Feature Request: First Person body not always facing where you are facing

### ISSUE THREAD

**Issue by Rainnifer** [ArranzCNL/ImprovedCameraSE#25]
Would it be possible to make it so we can set an angle of looking left or right before the body turns to face that direction? Even if it only works with weapons sheathed.

**Comment by ArranzCNL** [comment]
Yes it is and can do it for both but only for pure first person ie not VampireLord/Werewolf/Lich etc.

**Comment by Rainnifer** [comment]
That would be awesome!

**Comment by ArranzCNL** [comment]
Closing this on the radar, possibly for 1.1.0.
