### ISSUE TITLE
a conflict with FreeFlyCam

### ISSUE THREAD

**Issue by Sant90JH** [ArranzCNL/ImprovedCameraSE#27]
[FreeFlyCam](http://www.enbseries.enbdev.com/forum/viewtopic.php?t=5386)'s mouse scroll to adjust FOV doesn't work with ImprovedCamera
I thought it was just ImprovedCamera's FOV override feature locking things but disabling that didn't help

**Comment by ArranzCNL** [comment]
Unable to reproduce works as it has done since SE PR2.

Tested just now with default settings from Improved Camera SE PR3 and FreeFlyCamSKSE64_v12.1 (1.5.73-97)
No issues.

Has to be a conflict with a different mod.
