### ISSUE TITLE
Feature Request: Head bob only for Immersive Interactions

### ISSUE THREAD

**Issue by Alexander-Miller** [ArranzCNL/ImprovedCameraSE#28]
Enabling head bob provides great synergy with Immersive Interactions, letting you immersively kneel down to open a chest or pick a flower. However it feels rather terrible in most other circumstances, in particular there is a very ugly movement of the camera settling into a still position whenever you stop turning or moving. For these reasons it'd be great if there was an option to enable head bob only when interacting or standing still.

Here's 0na example showing both the good and bad parts of head bob: https://imgur.com/a/0481D25

**Comment by ArranzCNL** [comment]
Immersive Interactions you need to setup correctly.
Force 3rd Person
Disable Puzzles - breaks pulling levers.
Disable Saluting Jarls - breaks talking to Jarls who have a quest on them.
Disable Applauding Bards - breaks talking to bards who have a quest on them.

And disable Headbob in Improved Camera, as above does what you want!

**Comment by Alexander-Miller** [comment]
Technically you are right, but that kind of setup [is not exactly smooth either](https://imgur.com/a/kP6jc14). 
Would it be doable to toggle headbob only when no weapon is drawn? That would also cover Immersive Interactions and the camera issues are a lot less bad when there's no weapon.
