### ISSUE TITLE
Disappearing Player Arms

### ISSUE THREAD

**Issue by TortugoEXE** [ArranzCNL/ImprovedCameraSE#33]
Player's arms become invisible when equipping a bow in the idle stance in first person.

**Comment by noughtmare** [comment]
Yes, I see what is wrong. This was my mistake. I can fix it quickly, but I'm not sure how quickly we can do another stealth update.

Alternatively you can try enabling the `bThirdPersonArmsBow=1` or in game: Shift+Home->View->General->Third Person Arms Bow, that fixes the disappearing arms when the bow is sheathed, but it then also doesn't use the first person arms when the bow is drawn (but not when you're actually aiming/firing).

**Comment by noughtmare** [comment]
I've pushed a super stealth update: https://github.com/ArranzCNL/ImprovedCameraSE/releases/download/v1.0.0/ImprovedCameraSE-1.0.0.7z

**Comment by TortugoEXE** [comment]
You are amazing. Thank you!
