### ISSUE TITLE
Heavy arm model/crosshair misalignment with True Directional Movement and Nemesis

### ISSUE THREAD

**Issue by VenomNihil** [ArranzCNL/ImprovedCameraSE#34]
I'm not sure if this mod can do something about it or it should forwarded to Ershin for compatibility, but using the last 2 patches with True Directional Movement give me this camera "bug" when drawing a bow:
![nQ1fQGw](https://user-images.githubusercontent.com/73274471/188544188-72d872b1-9f84-45dc-acd1-0d5694df0ec6.png)
both with and without the optional Horse Archery addon for Nemesis that enables 360º mounted archery combat, only difference is that is less noticeable while not using the addon. When the bow is sheathed the camera looks normal:
![LyJZWL8](https://user-images.githubusercontent.com/73274471/188544274-8ac7d57f-10a2-4e7d-a1d5-3c51a756c96a.png)
(albeit maybe a bit to the right). Tried disabling AGO archery camera to no effect. Using both AGO and CGO, full modlist here: https://pastebin.com/Ak15Scxg 
Running only AGO and CGO also makes the mounted bow misaligned but not by much, it's pretty bearable.

**Comment by TwistedModding** [comment]
There are some issues with TDM and horseback riding in first person that arranz is aware of, full compatibility between the two will come at a later update, most likely after the nexus release (1.0)

**Comment by ArranzCNL** [comment]
Closing issue as, as noted it is a TDM issue full support for this will come with NG release.
