### ISSUE TITLE
Latest build doesnt load

### ISSUE THREAD

**Issue by zhongjiedong** [ArranzCNL/ImprovedCameraSE#35]
• ImprovedCameraSE version 1 (ImprovedCameraSE.dll, Improved Camera SE) disabled, fatal error occurred while loading plugin.

**Comment by noughtmare** [comment]
I cannot reproduce this on my machine. Maybe try downloading our mod again and reinstalling it?

**Comment by zhongjiedong** [comment]
Still the same, maybe  the update is now using an address another dll already reserved?

**Comment by TwistedModding** [comment]
Shouldn't be the case, a popup would appear showing the address that is being used.

**Comment by zhongjiedong** [comment]
ok nvm i had ini from previous version that was the issue
