### ISSUE TITLE
Flying glitch with Poise animations

### ISSUE THREAD

**Issue by VenomNihil** [ArranzCNL/ImprovedCameraSE#36]
Whenever poise + poisebreaker triggers a stagger animation in first person the player is sent flying at the end of the animation. bForceFirstPersonStagger in poisebreaker's ini doesn't have any impact. Everything works fine if I disable improved camera and leave the animations to play in third person only. See following video: https://streamable.com/zkmama If necessary I can post load order and modlist

**Comment by TwistedModding** [comment]
Can confirm this happened to me once a couple days ago rofl.

Unsure of the details or what happened prior though

**Comment by SpiritOfSuffering** [comment]
> [2\. Когда я прыгаю во время формы оборотня, игра иногда открывает "меню выбора переключения формы", чего я совсем не хочу(но это происходит). Когда я попытался выбрать вариант обращения обратно в человека, в тот момент, когда прыгнул в форме оборотня, то после анимации игра очень сильно подбросила меня в вверх и я из-за этого застрял в текстурах(и не смог выбраться).](https://github.com/ArranzCNL/ImprovedCameraSE/issues/39)

Я просто оставлю это здесь, т.к. моё сообщение об ошибке, частично связанно с тем, что вы продемонстрировали в своём видеоролике.

**Comment by skybaker** [comment]
Got the same issue. 

It happens only when both Poise Overhaul + Poisebreaker addon (as it is requires Poise Overhaul) are installed and bForceFirstPersonStagger=true in its ini. 
When player is knockedback and standing up, something forces player to 3rd person flying camera while real body of player still stays where it was upon landing after knockback. 
Switching back to 1st person fixes it, but every time I got knocked down, my camera switches back to 3rd person and flying away which is very annoying.
There is three temporary solutions:
 - disable Poisebreaker addon but which makes you literaturally imune to knockdowns
or
 - disable Improved Camera. Without it switching to 3rd person camera not makes player fly

PS. Switching bForceFirstPersonStagger to false didn't removes that glitch but still aplies knockback animation.

**Comment by xRinzler** [comment]
I also am having this issue, however I do not have Poise Overhaul installed nor have I ever had it installed.  Disabling this mod fixed my issue.

**Comment by krypto5863** [comment]
Can confirm this issue with this mod. In my case I'm just using Animal Tweaks that makes bears knock you down on some hits, but they absolutely ragdoll you and send you flying. It's brutal...

Edit: Enabling third person arms seems to resolve this issue completely. Might have to do with the havok mass of the 1st person meshes maybe?

**Comment by ArranzCNL** [comment]
@krypto5863 Oo interesting, I'll have to take a look at that mod.

Update on the Poise Issue:
Nearly have this working fully, no flybacks currently however getting pushed into third person needs resolving.


Update 15/01/23:
Final issue to resolve
- Poise causes a problem if the actor is restrained and restricted to first person aka Skyrim Intro.


Update 13/01/23:
Further testing required but this issue should be fully resolved now.

**Comment by ArranzCNL** [comment]
Fully fixed.
