### ISSUE TITLE
Start Screen CTD

### ISSUE THREAD

**Issue by Mastersuchef** [ArranzCNL/ImprovedCameraSE#37]
CTD when I get to the main menu screen. netscriptframework says it might be my d3d11.dll file. I use DXVK and it alters that dll file so that might be the problem. is there a fix for this? heres the improvedcameraSE.log.
[ImprovedCameraSE.log](https://github.com/ArranzCNL/ImprovedCameraSE/files/9544285/ImprovedCameraSE.log)

**Comment by ArranzCNL** [comment]
No workaround for this I'm afraid at least no quick fix only thing you can do is disable the menu. If it is still doing it after that then something must be wrong with DXVK as I believe Proton uses Vulkan under the hood which it works on but then again that could be a Linux vs Windows thing.

**Comment by TwistedModding** [comment]
You can also try installing reshade, it seems to help with crashes, and/or menu not showing up.
