### ISSUE TITLE
Баг с отсутствующей головой Лорда-вампира и застревание в текстурах

### ISSUE THREAD

**Issue by SpiritOfSuffering** [ArranzCNL/ImprovedCameraSE#39]
1) Если смотря в пол во время бега в форме Лорда-вампира, вы нажмёте вправо или влево и одновременно с этим прыжок, то сможете обнаружить, что голова у персонажа вовсе отсутствует, либо обрезается(я не знаю), потому что в этот момент мы смотрим прямо внутрь модели персонажа.
![ScreenShot20](https://user-images.githubusercontent.com/77529464/190863146-7929c27d-8a74-4a57-92e5-b7a0f9ce76a5.png)
![ScreenShot24](https://user-images.githubusercontent.com/77529464/190863161-e2b99aae-8b03-4d0d-b7da-125aadaa7a9a.png)
![ScreenShot26](https://user-images.githubusercontent.com/77529464/190863170-74ed66b2-d54c-4b94-831e-cca41249f2ab.png)

2) Когда я прыгаю во время формы оборотня, игра иногда открывает "меню выбора переключения формы", чего я совсем не хочу(но это происходит). Когда я попытался выбрать вариант обращения обратно в человека, в тот момент, когда прыгнул в форме оборотня, то после анимации игра очень сильно подбросила меня в вверх и я из-за этого застрял в текстурах(и не смог выбраться).
![ScreenShot27](https://user-images.githubusercontent.com/77529464/190863495-9d73a1c0-7f87-4920-b323-331cccb8ac89.png)
![ScreenShot28](https://user-images.githubusercontent.com/77529464/190863500-c6fc08f9-b369-4bf8-82d9-1667162e0b65.png)
![ScreenShot29](https://user-images.githubusercontent.com/77529464/190863506-18fadc81-4335-4f7b-8a91-ddc248a5a614.png)
![ScreenShot30](https://user-images.githubusercontent.com/77529464/190863513-cf5ba88f-f972-44db-827f-b49916c45276.png)

**Comment by ArranzCNL** [comment]
1) VampireLord shall need to take another look at it possibly nothing can be done just the way the animations work as the head is hidden by default due to clipping issues.

2) Werewolf issues should be resolved as was just testing during untransformation, jumping around like a mad hatter etc and saw no flybacks.
