### ISSUE TITLE
Smooth random jumping animation 

### ISSUE THREAD

**Issue by ALNth** [ArranzCNL/ImprovedCameraSE#40]
The mod that I have makes the player make kind of sneak roll after you land of a jumping, and well that movement in first person looks weird. Wondering if there's a way to hide the body at the moment; I've tried the option of hiding it when sneak rolling, and also while jumping but it doesn't do anything. Just wondering if there's a way to fix this without removing the jump mod animation

**Comment by TwistedModding** [comment]
Checking it out right now, I use the same mod but I don't recall having any clipping issues with it.

Edit:
Unable to reproduce. Maybe try disabling headbob if you have it enabled?

**Comment by ALNth** [comment]
Sorry for answering this late. 
It doesn't do a headbob; it just shows the body doing a roll, that's why I'd tried to hide the body when sneak rolling and jumping but still didn't do anything

**Comment by TwistedModding** [comment]
Ahh I understand, I dont think any setting will help with that since its a modded animation with no events linked to it

**Comment by ArranzCNL** [comment]
The hiding functionality doesn't work as of yet due to needing to implement the shadownode hook.
