### ISSUE TITLE
Improved Camera Crash

### ISSUE THREAD

**Issue by rubyr47** [ArranzCNL/ImprovedCameraSE#41]
1. it happen when i sheath weapon, the weapon will stay in hand and then character disappeared after that it crash
2. same but sometime it takes minute to crash but when i switch to first person it crash
3. sometime unexpected crash happen whether i just entered dungeon , door etc.

this is the crash log https://pastebin.pl/view/cb75611f

and this is editor config ini https://pastebin.pl/view/6387253b

the last file is improve camera.ini https://pastebin.pl/view/e653c46f

and mod order https://modwat.ch/u/Ruby

**Comment by ArranzCNL** [comment]
Something is interferring somehow what I do not know as this is the first time it has been reported of sheathing your weapon causing a crash.

Not really going to be much can do about that I'm afraid. We can't go through people's mod setups it is impossible.

**Comment by rubyr47** [comment]
is there any information you need orr maybe that's it?

hmm is FPCAO is the cause or no?

**Comment by TwistedModding** [comment]
Hey there, looking a bit deeper into the log reveals that it is possibly a skeleton issue. Try to install this mod: https://www.nexusmods.com/skyrimspecialedition/mods/1988 and have it overwrite everything

Let me know if it fixes it or not

**Comment by rubyr47** [comment]
alright, let me test it on my next holiday and see if it fixes.

thank you !
