### ISSUE TITLE
SmoothCam Arrow Prediction Freeze/Lag

### ISSUE THREAD

**Issue by Hansukie** [ArranzCNL/ImprovedCameraSE#43]
On v1.5.97, latest Improved Camera SE PR4 stealth update. 

Improved Camera SE PR4 worked fine with SmoothCam until very recently. 

For some reason, whenever an arrow is drawn in 3rd person and the SmoothCam arrow prediction crosshair is set to appear, the entire game freezes for around 60 seconds. Afterwards, the game seems fine. This never used to happen before. I have no idea why it's happening now. 

After every fresh bootup of the game and whenever an arrow is drawn, the 60 second freeze happens. 

The freezing stops if I turn off all the arrow prediction crosshair settings in SmoothCam's MCM, but that's not desirable. 

The freezing issue goes away if I disable Improved Camera. 

I noticed that this freezing issue didn't happen until after I installed True Directional Movement and PC Headtracking. However, even if I disable those mods the freezing issue persists. I wonder if those mods interfere with Improved Camera in some way and left something behind that doesn't get removed when disabled? 

EDIT: I just did some testing and versions PR2 and PR3 do not give me this freezing issue. So it looks like only PR4 has it.

**Comment by TwistedModding** [comment]
Can't reproduce on my end, I have all the aforementioned mods installed.

**Comment by Hansukie** [comment]
> Can't reproduce on my end, I have all the aforementioned mods installed.

What if you activate the headtracking option on both TDM and PC Headtracking?

Then restart your game, because the freezing won't happen if the arrow prediction crosshair is already loaded into memory.

**Comment by ArranzCNL** [comment]
Does this occur only once or multiple times within the play session? I know with 1.5.97 switched the D3D loading late like in 1.6.353+ as this had an issue with enbseries otherwise.

**Comment by Hansukie** [comment]
This only occurs once during the play session. 

I tested with PR2 and PR3 and the freezing issue doesn't happen with those.

**Comment by ArranzCNL** [comment]
Try setting MenuMode=1

Note:
Using MenuMode=1 means you have to be running Skyrim Borderless Fullscreen (not pure fullscreen) otherwise it'll cause flipping and won't work. If SmoothCam is doing it on this mode, SmoothCam author will need to fix however they are hooking the D3D device as this is solely Improved Camera's window.

Or you can just switch the menu off completely with MenuMode=0

I think PR2 and PR3 were originally using this mode as we were having issues with enbseries on AE.

**Comment by TwistedModding** [comment]
Also in the mean time, true directional movement has head tracking integrated if the above fix doesn't work.

**Comment by Hansukie** [comment]
For PR4, I tried using MenuMode=1 but now it won't get past the freeze anymore and I have to kill Skyrim in task manager using keyboard only because it somehow locks my mouse cursor up causing it to disappear. Not even alt+tab works to bring back the cursor. When Skyrim closes the mouse cursor returns.  

I am running Skyrim in Borderless Fullscreen. 

Switched back to PR2 and checked the settings. It uses MenuMode=2. Same thing with PR3. These don't have the freezing issue. 

@TwistedModding 
I'm aware of TDM having its own head tracking option. What does that have to do with the fix?

**Comment by ArranzCNL** [comment]
Just disable the menu altogether, it's the main reason I ended up with various modes as there are too many mods doing similar things and we all can't play nicely together unfortunately.
