### ISSUE TITLE
Incompatibility with new versions of Immersive Equipment Displays

### ISSUE THREAD

**Issue by TheMagnificentZ** [ArranzCNL/ImprovedCameraSE#44]
Just a heads-up. Not sure if compatibility issues are on the dev radar, but I figured I'd let you know since you're working on the next version. There's some kind of issue between Improved Camera (on preview 4 for SE) and Immersive Equipment Displays 1.6.0+ https://www.nexusmods.com/skyrimspecialedition/mods/62001

Doesn't effect IED, but shuts down ICSE entirely, at least on SE1.5.39/SKSE1.5.97. No visible first person body, no config menu, nothing. I don't have the AE so I don't know if it's replicable in newer versions of the game.

**Comment by TwistedModding** [comment]
I have the latest version of IED and im not having this issue

**Comment by TheMagnificentZ** [comment]
Are you using AE?

**Comment by TwistedModding** [comment]
Nope.

**Comment by DustyWantingMicrowave** [comment]
Having the same issue, using SE too

**Comment by TwistedModding** [comment]
Skyrim 1.5.39 is ancient and i dont know why you'd be on that version and a "1.5.97" skse version doesn't exist. 

Update Skyrim to 1.5.97 
Make sure you have the latest skse version supporting 1.5.97 
Make sure you downloaded the correct version of improved camera for your skyrim version.

**Comment by ArranzCNL** [comment]
I just tested this myself:
[See Here](https://imgur.com/a/J5OdMAs)

As you can clearly see both are working fine together.
