### ISSUE TITLE
Incompatibility with Minimap

### ISSUE THREAD

**Issue by taffy711** [ArranzCNL/ImprovedCameraSE#46]
There is a weird conflict with Minimap (https://www.nexusmods.com/skyrimspecialedition/mods/49490) where toggling the minimap on and off changes the FOV with Improved Camera installed. This wasn't an issue with the old Improved Camera.

**Comment by ArranzCNL** [comment]
Sorry for the late response on this. No doubt the MiniMap mod has its own FOV settings if they do not match what you have with Improved Camera that will result in what you are experiencing. We have a check in place for if the MapMenu is displayed and if so it turns off.
