### ISSUE TITLE
Player mouth floating in center of room

### ISSUE THREAD

**Issue by HaasJona** [ArranzCNL/ImprovedCameraSE#47]
I have a very weird glitch with ImprovedCamera (installed from here: https://github.com/ArranzCNL/ImprovedCameraSE/releases/tag/v1.0.0 from 05/09/2022 ), the player mouth is floating stationary in the center of the cell (presumably at 0/0 coordinates) instead of being properly in the mouth.

This only happens with ImprovedCamera installed.

![ScreenShot1](https://user-images.githubusercontent.com/4310707/197376428-affb324f-c263-4e48-9ca0-44a3e8c4d8bb.png)
![ScreenShot2](https://user-images.githubusercontent.com/4310707/197376443-f2d65048-2e47-48c2-befe-200334b75fce.png)

This is very visible in Hearthfire homes for example, where the mouth is floating at the far side from the entrance in the large main hall between the main table and the fireplace.

Some ini settings disabling the player head in first person make the mouth diappear in first person, but as soon as you switch to third-person, it appears again.

Running 1.6.353.0.8, SKSE 2.1.5 rel 6

**Comment by ArranzCNL** [comment]
This is the first time seeing/hearing of a glitch like this, has to be a mod conflict or skeleton model not setup correctly.

**Comment by HaasJona** [comment]
Thank you for your response. I messed around with uninstalling various mods and trying different things and found the solution. I simply had to use `showracemenu` and accept my character again and the floating mouth vanished. Looks like something got corrupted there.

Sorry for bothering you and continue the great work.
