### ISSUE TITLE
A reproducible CTD, and a whirlwind sprint to the sky

### ISSUE THREAD

**Issue by hikawasayotohina** [ArranzCNL/ImprovedCameraSE#49]
[Crash_2022_12_10_17-6-40.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/10202630/Crash_2022_12_10_17-6-40.txt)
[Crash_2022_12_12_0-9-58.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/10202632/Crash_2022_12_12_0-9-58.txt)
[Crash_2022_11_29_6-25-39.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/10107993/Crash_2022_11_29_6-25-39.txt)
[Crash_2022_10_29_16-46-2.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9894410/Crash_2022_10_29_16-46-2.txt)
[Crash_2022_10_29_16-36-58.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9894411/Crash_2022_10_29_16-36-58.txt)
Hello, I found two problems when using this mod

Drag the mouse wheel from the third person to the point before switching to the first person

Use whirlwind sprint will cause the character to fly to the sky

Using the sword shadow in "UltimateCombat" may cause the weapon to be stuck in the hand when closing the knife

At this time, entering the first person will lead to CTD

Use machine translation, which may be unclear

I recorded a video

Hope to help you understand something

1: Fly into the sky [https://youtu.be/lsgpZ3bNzL8](url)

2：CTD [https://youtu.be/ovzyBqCFwLo](url)

There are also CTD logs.
[Crash_2022_10_29_16-36-58.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9894414/Crash_2022_10_29_16-36-58.txt)
[Crash_2022_10_29_16-14-39.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9894417/Crash_2022_10_29_16-14-39.txt)
[Crash_2022_10_29_16-26-28.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9894419/Crash_2022_10_29_16-26-28.txt)
[Crash_2022_10_29_16-46-2.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9894420/Crash_2022_10_29_16-46-2.txt)
[Crash_2022_11_1_17-29-40.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9909078/Crash_2022_11_1_17-29-40.txt)
[Crash_2022_11_1_17-51-11.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/9909079/Crash_2022_11_1_17-51-11.txt)

**Comment by noughtmare** [comment]
Tip for posting the log: you can drag and drop files onto github text edit fields, see the that bar at the bottom that says: "Attach files by dragging & dropping, selecting or pasting them."

**Comment by hikawasayotohina** [comment]
Thank you. It's the first time I use this website. I don't understand some operations
