### ISSUE TITLE
Stopped working after an update of mods

### ISSUE THREAD

**Issue by Hero2500** [ArranzCNL/ImprovedCameraSE#51]
It was working until recently but when I updated some of my mods not skyrim,(v1.6.353) the mod stopped working, when I launch the game and load in, nothing shows, the menu of the mod works but no body in 1st person. Is there any incompatible mods causing this?

**Comment by TwistedModding** [comment]
can you post your improved camera log?

**Comment by Hero2500** [comment]
where do I find the log?

**Comment by TwistedModding** [comment]
Documents\My Games\Skyrim Special Edition\SKSE\ImprovedCameraSE.log

**Comment by Hero2500** [comment]
Here's the log

Improved Camera AE v1.0.0
[12/11/22 22:23:06] FileSystem Loading...
[12/11/22 22:23:06]   m_ApplicationPath:		Z:\Games\TES - Skyrim - Anniversary Edition\
[12/11/22 22:23:06]   m_PluginPath:			Z:\Games\TES - Skyrim - Anniversary Edition\Data\SKSE\Plugins\
[12/11/22 22:23:06] ConfigSystem Loading...
[12/11/22 22:23:06]   m_ConfigPath:			Z:\Games\TES - Skyrim - Anniversary Edition\Data\SKSE\Plugins\ImprovedCameraAE\
[12/11/22 22:23:06]   m_ConfigName:			ImprovedCameraAE.ini
[12/11/22 22:23:06]   m_ConfigFile:			Z:\Games\TES - Skyrim - Anniversary Edition\Data\SKSE\Plugins\ImprovedCameraAE\ImprovedCameraAE.ini
[12/11/22 22:23:06]   ReadSettings():			OK
[12/11/22 22:23:06] ConfigSystem Loaded.
[12/11/22 22:23:06]   m_ApplicationName:		SkyrimSE.exe
[12/11/22 22:23:06]   m_ApplicationVersion:		1.6.353.0
[12/11/22 22:23:06]   m_ApplicationBaseAddress:		0x00007FF643C00000
[12/11/22 22:23:06]   m_ApplicationImageSize:		0x00000000037A3000
[12/11/22 22:23:06] FileSystem Loaded.
[12/11/22 22:23:06] Checking for compatibility issues...
[12/11/22 22:23:06]   TrueDirectionalMovement v2.2.2.0 detected.
[12/11/22 22:23:06] Finished checking for compatibility issues.
[12/11/22 22:25:11] WindowSystem Loading...
[12/11/22 22:25:11]   m_pApplicationWindow.name:	Skyrim Special Edition
[12/11/22 22:25:12]   m_pApplicationWindow.handle:	0x0000000002C706BC
[12/11/22 22:25:12]   m_pApplicationWindow.width:	1920
[12/11/22 22:25:12]   m_pApplicationWindow.height:	1080
[12/11/22 22:25:12]   m_pApplicationWindow.posX:	0
[12/11/22 22:25:12]   m_pApplicationWindow.posY:	0
[12/11/22 22:25:12] D3D11System Loading...
[12/11/22 22:25:12]   Dirty Loader Found:		ENBSeries v0.4.7.5 (d3d11.dll)
[12/11/22 22:25:12]   Dirty Loader Found:		ReShade v5.4.2.1604 (dxgi.dll)
[12/11/22 22:25:13]   DirectX WindowHandle:		0x0000000002C706BC
[12/11/22 22:25:13] UIMenu Loading...
[12/11/22 22:25:13]   m_ImGuiFile:			Z:\Games\TES - Skyrim - Anniversary Edition\Data\SKSE\Plugins\ImprovedCameraAE\editorconfig.ini
[12/11/22 22:25:13]   customFont:			Z:\Games\TES - Skyrim - Anniversary Edition\Data\SKSE\Plugins\ImprovedCameraAE\Fonts\OpenSans\OpenSans-Regular.ttf
[12/11/22 22:25:13]   fontSize:				18.0
[12/11/22 22:25:13]   m_MenuKey:			0x24
[12/11/22 22:25:13] UIMenu Loaded.
[12/11/22 22:25:13]   MH_CreateHook:			[IDXGISwapChain] Present
[12/11/22 22:25:13] D3D11System Loaded.
[12/11/22 22:25:13]   Skyrim Special Edition:		Successfully subclassed main window
[12/11/22 22:25:13] WindowSystem Loaded.
[12/11/22 22:25:13] DInputSystem Loading...
[12/11/22 22:25:13]   MH_CreateHook:			[IDirectInputDevice8] GetDeviceState
[12/11/22 22:25:13]   MH_CreateHook:			[IDirectInputDevice8] GetDeviceData
[12/11/22 22:25:13] DInputSystem Loaded.

**Comment by TwistedModding** [comment]
can you also post your ini settings?

**Comment by Hero2500** [comment]
Here

[MODULE DATA]
; Application name along with version(s) supported
ApplicationName=SkyrimSE.exe
ApplicationMinVersion=1.6.318.0
ApplicationMaxVersion=1.6.999.0

; Application window name
WindowName=Skyrim Special Edition

; Performs an internal check on problematic plugins and will try to fix itself
CheckCompatibility=1

; Hook for DirectInput to stop keys and mouse being processed whilst Internal Menu is displayed (MenuMode=2)
;    0: Disabled
;    1: Block Keys and Mouse
HookInput=1

; Menu load style
;    0: Disabled - No menu loaded
;    1: External - Creates a window (glass effect) over the application (not recommended if using Fullscreen)
;    2: Internal - Embeds into the application
MenuMode=2

; Timeout to stop searching for the above WindowName in seconds
MenuTimeout=120

; Key modifier to open the menu, 0x24 is Home. Note: You need to hold down Left Shift before pressing the key
MenuKey=0x24

; Custom font, you can also use fonts from: "C:\Windows\Fonts\" ie MenuFont=micross.ttf (Don't include folder path)
MenuFont=OpenSans\OpenSans-Regular.ttf

; Custom font size
MenuFontSize=18.0


[GENERAL]
; Enables a visible body when in first person
bEnableBody=1

; Enables a visible body when the console is open
bEnableBodyConsole=0

; Enables shadows on the player when in first person
bEnableShadows=1

; Adjusts the first person camera height to match your character's race scale
bAdjustPlayerScale=1

; Moves the body in first person to adjust the camera height
fBodyHeightOffset=0.000000

; Enables the head node when in first person (may make hair visible)
bEnableHead=1
bEnableHeadHorse=1
bEnableHeadDragon=1
bEnableHeadWerewolf=0
bEnableHeadVampireLord=0
bEnableHeadScripted=0

; Enables third person arms when in first person
bEnableThirdPersonArms=0
bEnableThirdPersonArmsBow=0
bEnableThirdPersonArmsBowAim=0


[HIDE]
; Settings to hide weapons on back when in first person to prevent camera clipping
bHide2HWeapon=0
bHideBow=0
bHideQuiver=0

; Settings for hiding the body
bHideBodySitting=0
bHideBodySleeping=0
bHideBodyJumping=0
bHideBodySwimming=0
bHideBodySneakRoll=1
bHideBodyAttack=0
bHideBodyPowerAttack=0
bHideBodyAttackBow=0
bHideBodyKillmove=0


[FIXES]
; Holding the SwitchPOV key down while on a mount and moving the mouse changes the camera distance
; This the the minimum distance to detect if player is just tapping the SwitchPOV key
fSwitchPOVDetectDistance=0.030000

; Enables smooth animation transitions but also adds inertia when moving
bSmoothAnimationTransitions=0

; Used to set the amount of inertia, above needs to be enabled for fControllerBuffer1st to work
fControllerBuffer1st=0.010000
fControllerBuffer3rd=0.020000


[RESTRICT ANGLES]
; Sets the maximum angle you can look left/right whilst sitting
; Valid values between 0 and 90, Default: 90 (150 on cartride!)
fSittingRestrictAngle=80.000000

; Sets the maximum angle you can look up while sitting
; Valid values between 0 and 90, Game Default: 70
fSittingMaxLookingUp=45.000000

; Sets the maximum angle you can look down while sitting
; Valid values between 0 and 90, Game Default: 40
fSittingMaxLookingDown=70.000000

; Sets the maximum angle you can look left/right on horseback
; Valid values between 0 and 90, Default: 120
fMountedRestrictAngle=70.000000

; Sets the maximum angle you can look up during mounted combat
; Valid values between 0 and 90, Game Default: 70
fMountedMaxLookingUp=70.000000

; Sets the maximum angle you can look down during mounted combat
; Valid values between 0 and 90, Game Default: 30
fMountedMaxLookingDown=70.000000

; Sets the maximum angle you can look left/right while dragon riding
; Valid values between 0 and 90, Default: 120
fFlyingRestrictAngle=70.000000

; Sets the maximum angle you can look up while dragon riding
; Valid values between 0 and 90, Game Default: 70
fFlyingMaxLookingUp=70.000000

; Sets the maximum angle you can look down while dragon riding
; Valid values between 0 and 90, Game Default: 70
fFlyingMaxLookingDown=70.000000

; Sets the maximum angle you can look left/right for werewolf
; Valid values between 0 and 180, Default: 120
fWerewolfRestrictAngle=80.000000

; Sets the maximum angle you can look left/right for vampirelord
; Valid values between 0 and 180, Default: 120
fVampireLordRestrictAngle=80.000000

; Sets the maximum angle you can look left/right for necrolich
; Valid values between 0 and 180, Default: 120
fNecroLichRestrictAngle=80.000000

; Sets the maximum angle you can look left/right for scripted forced third person
; Valid values between 0 and 180, Default: 120
fScriptedRestrictAngle=50.000000

; Sets the maximum angle you can look up/down for scripted forced third person
; Valid values between 0 and 90, Game Default: 90
fScriptedRestrictPitch=50.000000

[EVENTS]
; Enables first person during events where the game normally switches to third person
bEventFirstPerson=1
bEventFurniture=1
bEventCrafting=1
bEventKillmove=1
bEventRagdoll=1
bEventDeath=1
bEventCannibal=1
bEventHorse=1
bEventHorseCombat=1
bEventHorseTransition=1
bEventDragon=1
bEventDragonCombat=1
bEventDragonTransition=1
bEventWerewolf=1
bEventVampireLord=1
bEventTransform=1
bEventNecroLich=1
bEventScripted=1
bEventThirdPerson=1


[FOV]
; Enables settings for changing fov
bEnableFOVOverride=1

; Settings for changing fov
fFOVFirstPerson=75.000000
fFOVFirstPersonHands=90.000000
fFOVCombat=80.000000
fFOVFurniture=80.000000
fFOVCrafting=80.000000
fFOVKillmove=80.000000
fFOVRagdoll=80.000000
fFOVDeath=80.000000
fFOVCannibal=80.000000
fFOVHorse=80.000000
fFOVHorseCombat=80.000000
fFOVHorseTransition=80.000000
fFOVDragon=80.000000
fFOVDragonCombat=80.000000
fFOVDragonTransition=80.000000
fFOVWerewolf=80.000000
fFOVVampireLord=80.000000
fFOVNecroLich=80.000000
fFOVScripted=75.000000
fFOVThirdPerson=80.000000


[NEARDISTANCE]
; Enable settings for changing fNearDistance
bEnableNearDistanceOverride=1

; Settings for changing fNearDistance
; Pitch Threshold for changing the fNearDistance automatically
fNearDistancePitchThreshold=-69.000000

; Reduce fNearDistance when Pitch Threshold is met
fNearDistanceFirstPerson=4.000000
; The following are independent from the Threshold
fNearDistanceSitting=15.000000
fNearDistanceFurniture=4.000000
fNearDistanceCrafting=4.000000
fNearDistanceKillmove=4.000000
fNearDistanceRagdoll=4.000000
fNearDistanceDeath=4.000000
fNearDistanceCannibal=4.000000
fNearDistanceHorse=15.000000
fNearDistanceHorseCombat=15.000000
fNearDistanceHorseTransition=2.000000
fNearDistanceDragon=15.000000
fNearDistanceDragonCombat=15.000000
fNearDistanceDragonTransition=2.000000
fNearDistanceWerewolf=15.000000
fNearDistanceVampireLord=15.000000
fNearDistanceNecroLich=15.000000
fNearDistanceScripted=2.000000
fNearDistanceThirdPerson=15.000000


[HEADBOB]
; Enables the head bob when in first person
; Position setting match the camera to head position. 0 - Disabled, 1 - Enabled
; Note: This overrides the camera position and may not be as compatible with some animations
bEnableHeadBobPositionIdle=0
bEnableHeadBobPositionWalk=0
bEnableHeadBobPositionRun=0
bEnableHeadBobPositionSprint=0
bEnableHeadBobPositionCombat=0
bEnableHeadBobPositionSneak=0
bEnableHeadBobPositionSneakRoll=0

; Rotation settings match camera rotation to head rotation
; Valid values between 0.0 and 1.0 controlling the amount of rotation
fHeadBobRotationIdle=0.000000
fHeadBobRotationWalk=0.000000
fHeadBobRotationRun=0.000000
fHeadBobRotationSprint=0.000000
fHeadBobRotationCombat=0.000000
fHeadBobRotationSneak=0.000000
fHeadBobRotationSneakRoll=0.000000


[CAMERA]
; Sets camera position relative to the head node
; Note: Only moves the camera if head bob is enabled, otherwise moves the body
fCameraPosX=0.000000
fCameraPosY=19.000000
fCameraPosZ=5.000000

; Sets the camera position for horse riding
fHorseCameraPosX=0.000000
fHorseCameraPosY=19.000000
fHorseCameraPosZ=5.000000

; Sets the camera position for horse riding combat
fHorseCombatCameraPosX=0.000000
fHorseCombatCameraPosY=19.000000
fHorseCombatCameraPosZ=5.000000

; Sets the camera position for dragon riding
fDragonCameraPosX=0.000000
fDragonCameraPosY=19.000000
fDragonCameraPosZ=5.000000

; Sets the camera position for vampirelord
fVampireLordCameraPosX=0.000000
fVampireLordCameraPosY=15.000000
fVampireLordCameraPosZ=7.000000

; Sets the camera position for werewolf
fWerewolfCameraPosX=0.000000
fWerewolfCameraPosY=85.000000
fWerewolfCameraPosZ=0.000000

; Sets the camera position for necrolich
fNecroLichCameraPosX=2.000000
fNecroLichCameraPosY=27.000000
fNecroLichCameraPosZ=15.000000

; Sets the camera position for scripted forced third person
fScriptedCameraPosX=0.000000
fScriptedCameraPosY=0.000000
fScriptedCameraPosZ=9.000000
