### ISSUE TITLE
CTD on game start

### ISSUE THREAD

**Issue by tallubhai** [ArranzCNL/ImprovedCameraSE#52]
My game crashes a couple seconds into the main loading screen. Crash log only has one line:

Unhandled exception "EXCEPTION_STACK_OVERFLOW" at 0x7FFC7FE1DBC7 nvwgf2umx.dll+1B0DBC7	mov byte ptr [r11], 0x00

ICSE log:
[ImprovedCameraSE.log](https://github.com/ArranzCNL/ImprovedCameraSE/files/10027792/ImprovedCameraSE.log)

Game version 1.5.97, skse ver. 2.0.20

Game launches perfectly fine without ICSE, which leads me to believe this mod is the culprit.

**Comment by ArranzCNL** [comment]
Thats an nvidia driver crash you need to perform a clean install.
[See Here](https://www.reddit.com/r/ffxiv/comments/gqz64b/game_crashing_w_nvwgf2umxdll_errors_fix/)
