### ISSUE TITLE
Concentration spells come out of the wrong spot in 1st person

### ISSUE THREAD

**Issue by Nickesponja** [ArranzCNL/ImprovedCameraSE#53]
[Images](https://imgur.com/a/A8FY142). Happens with vanilla and modded spells, only with the mod on. It's purely visual but a bit jarring.

**Comment by ArranzCNL** [comment]
Issue is not present in current dev build.

However the issue might be related to [Customizable Camera](https://www.nexusmods.com/skyrimspecialedition/mods/12201) which would mean Proper Aiming needs disabling from that.
