### ISSUE TITLE
Swap Chain Error Detected

### ISSUE THREAD

**Issue by CamaraderieKhaz** [ArranzCNL/ImprovedCameraSE#54]
"You are about to crash due to Swapchain Issues" Does anyone else have this problem or is it only me. Whenever I try to launch the game it just crashes and shows that message in front of me. I would really want an answer to this as it is actively preventing me from using this mod

**Comment by AtlasOrigins** [comment]
If I am not mistaken the mod is currently undergoing an update, please see [here](https://github.com/ArranzCNL/ImprovedCameraSE/issues/42#issuecomment-1313550663). It may be possible you will need to wait like the rest of us unfortunately.

**Comment by ghost** [comment]
> "You are about to crash due to Swapchain Issues" Does anyone else have this problem or is it only me. Whenever I try to launch the game it just crashes and shows that message in front of me. I would really want an answer to this as it is actively preventing me from using this mod

Disable smoothcam, from my own experience it causes this exact error.

**Comment by ArranzCNL** [comment]
This issue is due to SmoothCam and DetectionMeter however if ENB and/or ReShade are installed their is no issue.
