### ISSUE TITLE
Clear Skies shout no projectile in 1st person

### ISSUE THREAD

**Issue by OrrieL** [ArranzCNL/ImprovedCameraSE#56]
Clear Skies shout projectile does not always come out from 1st person.
If this happens then I have to draw a weapon, switch to 3rd person, shout, switch back to 1st, then projectile works even in 1st person.
ICSE PR4, SE 1.5.97

**Comment by xLaReL** [comment]
+1

Noticed that too..

**Comment by ArranzCNL** [comment]
Is it just the very first projectile doing this? I noticed something similar with the gun mod I was playing around with the very first bullet or bolt was way off.

**Comment by OrrieL** [comment]
> Is it just the very first projectile doing this? I noticed something similar with the gun mod I was playing around with the very first bullet or bolt was way off.

No, even repeated shouts, switching to 3rd and back to 1st does not fix it, switching to 3rd, drawing a weapon, going to 1st fixes the issue.

**Comment by ArranzCNL** [comment]
Bug confirmed.

Not even sure what is going on there as other shouts are working fine.

**Comment by ArranzCNL** [comment]
Somehow it is now fixed in Hotfix 3... I ain't asking questions!
