### ISSUE TITLE
Torches have 3rd person anim in 1st person 

### ISSUE THREAD

**Issue by majorpluto** [ArranzCNL/ImprovedCameraSE#59]
Torches use 3rd person anims when equipped in first person causing the torches to awkwardly be held by the player character out of view offscreen. Playing around with GUI menu options does nothing to remedy this. This was tested with only improved camera installed.

**Comment by ArranzCNL** [comment]
I shall take a look when I redo my Skyrim save points again. It could be FOV is set too close, game default is 80 or you have enabled third person arms which uses the third person location instead of first.

**Comment by majorpluto** [comment]
> 

Thanks for the reply. It's definitely not fov, I can see the third-person arm posture for holding the torch in the corner of my screen, if I pull out a weapon while holding a torch the posture is fine though. I scrolled through the GUI many times, third person arms were not enabled. I thoroughly looked through the GUI options and experimented with them, but nothing made any difference.

**Comment by ArranzCNL** [comment]
If you can take some screenshots that would be grand, going to look at this later with modded and unmodded setup. I'll upload screenshots once done.

**Comment by majorpluto** [comment]
I uploaded a video of the glitch here: https://www.youtube.com/watch?v=7qzEIQoFAkk

**Comment by ArranzCNL** [comment]
Oh wow that is way out of view!
Try altering fFOVFirstPersonHands default is set to 80.

Either way I shall take a look 100% tonight at this!

**Comment by ArranzCNL** [comment]
Fixed in upcoming build.
