### ISSUE TITLE
Signature Error (#574600) with HDT-SMP Force Fields - SkyrimSE v1.6.x

### ISSUE THREAD

**Issue by luvtrvp** [ArranzCNL/ImprovedCameraSE#61]
![error](https://user-images.githubusercontent.com/119896736/205743879-78e8d34d-1b2f-4a94-b5ea-cd27a030360a.png)

I'm unable to run the game at all with the latest version of this mod (I'm on game version 1.6.353). It was working then it stopped one time and I haven't been able to use it since. (The game runs fine without this mod checked in MO2) However, I'm hoping to find a fix for it because this mod absolutely transforms my 1st person gameplay.

**Comment by ArranzCNL** [comment]
Can you supply your SKSE mod list as this has to be coming from another mod using ModelReferenceEffect. Lucky I still have 1.6.353 installed so I can test against!

**Comment by iam3rr0r** [comment]
I had this similar issue. The mod in question is this one [https://www.nexusmods.com/skyrimspecialedition/mods/79899](url) There's a temporary fix in the stickied post on the mod page.

**Comment by luvtrvp** [comment]
I disabled my modlist one by one and managed to find the issue... It was this mod here https://www.nexusmods.com/skyrimspecialedition/mods/79899 You were right iam3rr0r, I just wasn't able to use your link for some odd reason Thanks for the assistance!

**Comment by iam3rr0r** [comment]
No problem. I am glad it helped you.

**Comment by ArranzCNL** [comment]
Just reopening this so it is on my radar to fix the address

**Comment by ArranzCNL** [comment]
Fixed in upcoming build.
