### ISSUE TITLE
DLL is incompatible with HDT-SMP Forcefields on SSE 1.5.97.0

### ISSUE THREAD

**Issue by FardeenRiyadh16** [ArranzCNL/ImprovedCameraSE#62]
![image](https://user-images.githubusercontent.com/102830787/206011397-09fada39-9550-41f3-af8b-dbc5fcc9bc7c.png)

Incompatible

**Comment by ArranzCNL** [comment]
Thanks for the report on the other address.

If you rename HDT-SMP Force Fields.dll to zHDT-SMP Force Fields.dll
It should work without any hassle for the time being.

**Comment by ArranzCNL** [comment]
Fixed in upcoming build.
