### ISSUE TITLE
News of upcoming Skyrim DLSS Support Incompatibility 

### ISSUE THREAD

**Issue by FardeenRiyadh16** [ArranzCNL/ImprovedCameraSE#63]
https://www.reddit.com/r/skyrimmods/comments/zfipo9/comment/izcgdzl/?utm_source=share&utm_medium=web2x&context=3

According to the comment, the Improved Camera Menu will conflict with the DLSS Mod coming soon, just wanted to know if you know of this and if there is going to be a fix, since I'm still tweaking my camera since I only recently found out it has one, and since I haven't been playing Skyrim SE much

**Comment by ArranzCNL** [comment]
I've heard about this and hasn't been tested with the current changes however it possibly still fails. Installing ReShade fixes the issue but is not an ideal solution.

I do plan on properly looking at DirectX 11/12 over the holidays and maybe try and workout how ReShade manages to resolve this issue.

**Comment by ArranzCNL** [comment]
Just to give a follow up on this Improved Camera can work with this however... GameOverlayRenderer64.dll (steam overlay) is the main culprit for the crashing issues. Current workaround is to rename the file upon steam launch as disabling via steam does nothing or install ReShade.

This is for all mods that implement some form of UI for example Smoothcam and Skyrim Platform will cause a crash due if GameOverlayRenderer64.dll (without IC). Rename that dll they play nicely together.

**Comment by FardeenRiyadh16** [comment]
Ok I have ReShade installed, I've been combining it with ENB for a while now, so I should be fine?

**Comment by ArranzCNL** [comment]
Yeah you should be fine with ReShade installed.

**Comment by ArranzCNL** [comment]
Closing as had some pointers from Pure Dark. Will require ReShade but Improved Camera's menu for the next release will be supported.
