### ISSUE TITLE
The game Skyrim SE does not start due to an error:

### ISSUE THREAD

**Issue by Velezarius** [ArranzCNL/ImprovedCameraSE#64]
Universal DLL Project

Signature with search start=558fc0 not found!
Module that caused this error: ImprovedCameraSE.dll
Please remove the mod with that DLL and report a capture of this error to the author!

**Comment by ArranzCNL** [comment]
Temporary workaround is to rename HDT-SMP Force Fields.dll to:
zHDT-SMP Force Fields.dll

Already fixed in upcoming release.
