### ISSUE TITLE
Camera keeps shooting to furthest left or right on horse

### ISSUE THREAD

**Issue by Gamer363636** [ArranzCNL/ImprovedCameraSE#65]
When i am riding a horse and moving the camera keeps shooting over to the furthest right or left changing the direction I'm looking and then going. It happens every few seconds making it pretty much impossible to use the horse in first person.

**Comment by ArranzCNL** [comment]
Never seen that must be a mod conflict with something as we do restrict how far you can look left/right otherwise Exorcist moment will occur.

**Comment by ArranzCNL** [comment]
TDM issue.
