### ISSUE TITLE
Encountering DLL Error when booting up game

### ISSUE THREAD

**Issue by AlexClan** [ArranzCNL/ImprovedCameraSE#67]
"Signature with search_start=558fc0 not found!

Module that caused this error: ImprovedCameraSE.dll

Please remove the mod with that DLL and report a capture of this error to the author"

Immersive Camera PR 4 is loaded last in MO2 modlist
Skyrim: 1.5.97 
SKSE: 2.0.20
Modwatch: https://modwat.ch/u/AlexanderClan

**Comment by DarthGamerV** [comment]
Just faced the same issue. IDK why

**Comment by JeremiahRoland** [comment]
I have the same issue. It popped up when I installed the newly released Skyrim Upscaler mod by PureDark. The error pops up when one of the dependencies for that mod are installed, located here: https://www.nexusmods.com/site/mods/491.

**Comment by SpaceArchitecture** [comment]
Same here, how strange

**Comment by ArranzCNL** [comment]
FYI it doesn't matter of loadorder of SKSE mods they are loaded alphabetically, regardless where you place them in MO2.


HDT-SMP Force Fields issue which is resolved in upcoming release.

Temp workaround rename:
HDT-SMP Force Fields.dll

To:
zHDT-SMP Force Fields.dll
