### ISSUE TITLE
Universal DLL Project error

### ISSUE THREAD

**Issue by Fue34** [ArranzCNL/ImprovedCameraSE#69]
Improved Camera pr4 SE installed and this is the message I get in a pop up from From Universal DLL Project when running SkyrimSE:

Signature with seach_start=26f17c not found

Module that caused this error:ImprovedCameraSE.dll

Please remove the mod with that DLL and report a capture of this error to the author.

![Screenshot (140)](https://user-images.githubusercontent.com/108565936/207534236-3cf13473-5791-4a0d-9587-23609f79ddc9.png)

**Comment by ArranzCNL** [comment]
I'll need to know all the skse plugins you are loading. I have around 40 skse mods loaded without seeing this issue.

As seen here:
![mo2_skse1](https://user-images.githubusercontent.com/52199624/207562527-091eda39-7ceb-4ba0-8a11-8042aaf98991.jpg)
![mo2_skse2](https://user-images.githubusercontent.com/52199624/207562521-e3827d64-5d4a-48bb-8f30-10159134133d.jpg)

**Comment by ProfessorMutant** [comment]
I just got this error myself, it was resolved after disabling "HDT-SMP force fields". (hope this info is helpful in any way)

**Comment by ArranzCNL** [comment]
@ProfessorMutant 
That would be a different signature(s) see here how to resolve for [HDT-SMP Force Fields](https://github.com/ArranzCNL/ImprovedCameraSE/issues/67)

I've heard about this other signature (#26F17C - _GetNiNode) in the past but none got back to me which mod it is coming from.

**Comment by ProfessorMutant** [comment]
ah right you are, the error code mine's throwing is 558fc0, not 26f17c. my bad.

(also, thanks for linking the resolution to the error, I'm assuming this workaround works by just forcing hdtsmp force fields to load last?)

**Comment by Fue34** [comment]
Super wierd. I checked through my skse dll list, re-deployed and now I can only produce the 558fc0 error. I did the HDT-SMP forcefield temp fix and my game loads now.

Possibly 26f17c is a transient error? No idea if that is possible or not.

If i get the error code again, Ill post.

**Comment by ArranzCNL** [comment]
Least you found the cause and have it working again, that is the main thing!

That is really weird, as the setup for _GetNiNode is 8 hooks prior to _ModelReferenceEffect2.
