### ISSUE TITLE
Giant arrow bug 

### ISSUE THREAD

**Issue by majorpluto** [ArranzCNL/ImprovedCameraSE#70]
When arrows land directly into the player's face such that the arrow is sticking directly out of the camera in first person, the arrow becomes massive: https://imgur.com/gallery/Q4rTl7T
The bug doesn't happen whenever the arrow impales the player's head, only the face in first person. 

This issue is amplified by archery gameplay overhaul because it increases the tendency for arrows to impale the player. I have fixed this bug by installing No Arrow In My Body SSE which prevents arrow impaling altogether but this is only a bandaid solution.

**Comment by Sloowey** [comment]
Pretty realistic imo, best pov

**Comment by TwistedModding** [comment]
Does this happen without improved camera installed?

**Comment by ArranzCNL** [comment]
Taking another look at the screenshot either another mod is screwing something up or it is a skyrim engine issue. If you look carefully at the base of the arrow you can see it is behind the buildings/trees which shouldn't be possible considering you can tell the screenshot is taken up high overlooking Riften.

**Comment by ArranzCNL** [comment]
Due to it looking like a another mod doing something dodgy this won't be fixed.

Workaround solution is to install:
[No Arrow In My Body SSE](https://www.nexusmods.com/skyrimspecialedition/mods/31690?tab=description)
