### ISSUE TITLE
Improved Camera preventing Skyrim from launching.

### ISSUE THREAD

**Issue by jimujimujimu** [ArranzCNL/ImprovedCameraSE#72]
![image](https://user-images.githubusercontent.com/121140575/208796520-149b01eb-ee81-4bfc-abac-d4df18bdef59.png)
I get this error every time i try to launch the game, i disabled the addon i use for Imp. Cam. and still get the same exact popup, my Skyrim version is 1.5.97, i'm using Improved Camera PR 4 1.5.x. I cannot find anything online that helps fix this.

**Comment by ArranzCNL** [comment]
HDT-Force Fields causes this.

Current workaround is to rename HDT-SMP Force Fields.dll to zHDT-SMP Force Fields.dll

**Comment by jimujimujimu** [comment]
changing the file named fixed it, everything is working as it should, thank you so much <3
