### ISSUE TITLE
Error with signature search_start=26f17c

### ISSUE THREAD

**Issue by X1toma** [ArranzCNL/ImprovedCameraSE#73]
![image](https://user-images.githubusercontent.com/76225955/209474908-855d273e-0d90-4f18-819f-42621ec1c1fc.png)
I did an assembly based on RFAB, all mods work fine. But the mod on the camera does not allow you to launch skyrim.

**Comment by ArranzCNL** [comment]
There is a conflict with another mod, I need to know all installed SKSE mods. Others have reported this before but then say it just works which is making me suspicious if it is some form of NSFW mod which I personally don't care about I just need to know which mod is conflicting so I can test against it, move the signature and comment it.

**Comment by Breakinger** [comment]
> There is a conflict with another mod, I need to know all installed SKSE mods. Others have reported this before but then say it just works which is making me suspicious if it is some form of NSFW mod which I personally don't care about I just need to know which mod is conflicting so I can test against it, move the signature and comment it.

Hey, I have the same issue, as you said, it might be NSFW mods, well the only NSFW I personally have CBPC and Maximum Carnage

Could one of those be culprits?

**Comment by ArranzCNL** [comment]
Maximum Carnage is just a normal skyrim addon (non-skse).

My mod setup for Skyrim v1.5.97 with SKSE mods is as follows:
Note: ENBSeries & ReShade are also active.

- +OStim NG - OSA Overhaul and API Next Gen
- +Show Animation Command
- +Improved Camera SE
- +CBPC - Physics with Collisions
- +HDT-SMP Force Fields
- +Faster HDT-SMP
- +Dynamic Collision Adjustment
- +Precision
- +True Directional Movement - Modernized Third Person Gameplay
- +TrueHUD - HUD Additions
- +SmoothCam
- +Poisebreaker - A Poise Mod Addon
- +POISE - Stagger Overhaul SKSE
- +Alternate Conversation Camera
- +Detection Meter - NG
- +Splashes Of Storms
- +Splashes of Skyrim
- +Moons And Stars - Sky Overhaul SKSE
- +Skyrim Souls RE - Updated
- +RaceMenu 0.4.16 Memory Leak Hotfix (SE)
- +RaceMenu
- +More Informative Console
- +Go to bed
- +Better Jumping SE
- +Sound Record Distributor
- +Spell Perk Item Distributor
- +Dynamic Animation Replacer
- +Animation Motion Revolution
- +Frozen Electrocuted Combustion
- +ENB Helper SE
- +Fuz Ro D-oh - Silent Voice
- +Mfg Fix
- +MCM Helper
- +Actor Limit Fix
- +Base Object Swapper
- +powerofthree's Papyrus Extender
- +powerofthree's Tweaks
- +PapyrusUtil SE - Modders Scripting Utility Functions
- +FileAccess Interface for Skyrim SE Scripts - FISSES
- +JContainers SE
- +ConsoleUtilSSE NG
- +Skyrim Upscaler - DLSS FSR2 XeSS
- +ShaderTools Updated
- +Bug Fixes SSE
- +SSE Engine Fixes (skse64 plugin)
- +Address Library for SKSE Plugins
- +Crash Logger SSE AE VR - PDB support

**Comment by TwistedModding** [comment]
try disabling HDT-SMP force fields, I know that one has a conflicting address.

**Comment by TwistedModding** [comment]
A list of mods would be helpful, I can check against my list to determine which one it is as I have about 150 skse plugins.

**Comment by vsTerminus** [comment]
I was experiencing this as well (Signature 574600, version 1.6.353). 

In my case it was this one: https://www.nexusmods.com/skyrimspecialedition/mods/79899?tab=posts

"HDT-SMP Force Fields" The comments section has a bunch of people reporting incompatibility with ImprovedCamera

**Comment by X1toma** [comment]
> There is a conflict with another mod, I need to know all installed SKSE mods. Others have reported this before but then say it just works which is making me suspicious if it is some form of NSFW mod which I personally don't care about I just need to know which mod is conflicting so I can test against it, move the signature and comment it.

I played with RFAB mods 8.7

**Comment by ArranzCNL** [comment]
@vsTerminus that is a completely different issue and has been resolved just unreleased at present.

@X1toma I'll take a look later currently downloading RFAB SE X, hope this is the right one.
