### ISSUE TITLE
Sluggish controls in first person camera

### ISSUE THREAD

**Issue by yytelliot** [ArranzCNL/ImprovedCameraSE#74]
It seems like there is a noticable amount of input lag when moving around in first person, certainly more than in vanilla or Improved Camera 1.

**Comment by ArranzCNL** [comment]
Sometimes it just happens and need to switch views (does this in vanilla) other than that only other reason that would happen is due to:
bSmoothAnimationTransitions=1

The default is 0.

Polling rate on your keyboard matters as well, standard is 250hz I believe.

**Comment by yytelliot** [comment]
The lag still happens when bSmoothAnimationTransitions=0. It is slight but noticeably more in the first person compared to vanilla or improved camera 1. I'm testing using the same keyboard so I don't think polling rate is the issue. If it helps, the lag is much worse when head bobbing is turned off, when it is on it is negligible enough not to affect gameplay as much even though it is still noticeable.

**Comment by ArranzCNL** [comment]
The only thing it can be is your using an older version as it was fully fixed in PR4+

**Comment by yytelliot** [comment]
Oh darn, you're right. Didn't notice the update, thanks! Keep up the good work :)
