### ISSUE TITLE
Misaligned Projectiles When in 1st Person

### ISSUE THREAD

**Issue by JeremiahRoland** [ArranzCNL/ImprovedCameraSE#75]
When trying to shoot magic based projectiles, they are greatly misaligned. This is most notable with the ice spikes, as it requires me to aim my reticle a good bit above my target, even when close to them. Additionally, there are instances where a magic projectile (such as a fire bolt),  are shot off to the left or right of my character. The only fix for this that I've found is to go into 3rd person then back to 1st.
Kind of unrelated, but sometimes when I use a shout nothing will actually happen. This typically only happens once, then when I try to use the shout again it works as normal. It's only happened when using this mod, but maybe that's just a Skyrim thing.

**Comment by ArranzCNL** [comment]
Undergoing Testing:
- Bows - Working as intended.
- Magic Projectiles - Working as intended.
- Magic Concentration - Working as intended.
- Magic Master - Working as intended.
- Shouts - Working as intended.
- Crossbows - Working as intended.
- Mounted Bows -Working as good as it can do for now.

Note this is from the dev build being worked upon.

**Comment by JeremiahRoland** [comment]
Yeah, I've seen this issue pop up every now and then on my recent playthrough without this mod present. So it's certainly something on my end. Sorry

**Comment by ArranzCNL** [comment]
Re-opened so I remember what to carrying on testing :)

**Comment by JeremiahRoland** [comment]
After some more testing, I found the issue was from Customizable Camera by SirArindel. It was the "Proper Aiming" feature, but I'm unsure of what specifically about that feature was causing the issue.

**Comment by ArranzCNL** [comment]
That is good to know I just had a quick look at the mod and a post dated from the 22/01/23 actually mentioned about arrows and magic projectiles being off with Proper Aiming enabled.

**Comment by JeremiahRoland** [comment]
Lol, yeah that was me. Wanted to make sure the OG mod author knew of the issue
