### ISSUE TITLE
Immersive Equipment Displays (fix)

### ISSUE THREAD

**Issue by Frassensh** [ArranzCNL/ImprovedCameraSE#76]
Hi! 
When I use this mod together wid IED I get no body in first person mode and crash when changing anything in the menu.
In the crash log it mentions skeleton.nif
Only crashes menu if im actually in first person mode. 
Skyrim 1.5.97
I fixed it by renaming ImprovedCameraSE.dll to aImprovedCameraSE.dll making it load before Immersive Equipment Displays.

**Comment by ArranzCNL** [comment]
Although that is a workaround, I am wondering what settings are active from IED for this to occur. Using default not touching anything doesn't cause any issues.

**Comment by Frassensh** [comment]
Ive attached my Settings.JSON if that helps you.
Im using this preset and ive customized it a bit iirc
https://www.nexusmods.com/skyrimspecialedition/mods/62449

[Settings.zip](https://github.com/ArranzCNL/ImprovedCameraSE/files/10361735/Settings.zip)
