### ISSUE TITLE
Equipping Bow in 1st Person Causes Crippling Lag When Wearing Certain SMP Outfits

### ISSUE THREAD

**Issue by Hansukie** [ArranzCNL/ImprovedCameraSE#79]
When holding a bow in your hands in first person view there is a huge lag wave that continues until you go out of 1st person view or sheathe the bow. During the lag, CPU usage jumps to 100% and the game becomes a single digit fps slideshow. 

This only seems to happen when wearing certain outfits that have SMP physics on the arms such as the "Outerwear SMP" part from [https://www.rektasmarket.com/post/coco-mysterious-mage](https://www.rektasmarket.com/post/coco-mysterious-mage). 

Just did some more testing and this seems to happen when any weapon is equipped in 1st person view with the Outerwear SMP equipped. 

Looking at the player character shadow during the lag event, the SMP parts seems to just stretch into infinity. 

Tested with ImprovedCamera disabled and the problem goes away.

**Comment by TwistedModding** [comment]
If the physics are bugging out in first person that has nothing to do with improved camera. And if its only specific hdt enabled mods, then its even less to do with us. Report this to the author that armor.

It could be a combination of your animations and which ones are getting played in first person, or the xml is setup improperly.

**Comment by Hansukie** [comment]
The issue goes away if ImprovedCamera is disabled though. Without Improved camera, in first person view, everything is fine. 

So wouldn't that mean that Improved Camera has something to do with it?

**Comment by TwistedModding** [comment]
Well one can assume, that because it happens in first person, it is because the body is now actually there in first person. 

Improved camera has nothing to do with it because it doesn't modify hdt in any way, and like i said previously, if it's only on one, or a select few armors. It is the armor mod at fault, not improved camera.

**Comment by Hansukie** [comment]
It seems to happen with every single armor mod that has equipment SMP physics on the arms. Mods that are from different authors. 

I can only assume that Improved Camera does something to the arms when it switches from weapon drawn and sheathed states and that causes the SMP arm equipment to spaz out and cause the lag. 

So I guess this means that Improved Camera isn't compatible with any armor mods that have SMP physics on the arms?

**Comment by ArranzCNL** [comment]
@Hansukie can you test your setup with third person arms enabled, it shouldn't cause the issue then.

By default when the 3rd person model is displayed and a weapon is drawn we shrink the arms up into the shoulder sockets unless third person arms is enabled.

Above should fix the issue but it would mean you cannot use normal first person hands with that type of armor set enabled.

**Comment by Hansukie** [comment]
@ArranzCNL Thanks a lot!

Yea, enabling thirds person arms definitely makes the issue go away, but like you said, normal 1st person hands won't be usable with this type of armor equipped. 

I'm guessing having the third person arms shrink to hide them when a weapon is drawn was the best implementation. However, it does have the side effect of causing arm armor with physics to propagate lag. 

I assume there won't be a way to fix this bug with the current way hiding arms works. 
Unless you come up with a new way to hide the arms that don't have side effects, but that's probably difficult as you probably have already thought about the best way to hide the arms.

**Comment by ArranzCNL** [comment]
I cannot see a viable solution to support ordinary first person hands along with physics on the arms unless we can find a different method other than shrinking them.

**Comment by ArranzCNL** [comment]
Closing this as only way for both physics arms and improved camera to work in harmony is to enabled third person arms.
