### ISSUE TITLE
Comptatablity issue with zxlice's ultimate potion animation

### ISSUE THREAD

**Issue by majorpluto** [ArranzCNL/ImprovedCameraSE#81]
When drinking potion in first person with no weapon equipped the first-person drink animation doesn't play.

**Comment by ArranzCNL** [comment]
@majorpluto Does the animation play if the weapon is drawn?

**Comment by majorpluto** [comment]
Yes

**Comment by ArranzCNL** [comment]
Ok I shall take a look this evening as the fixes I've applied to AnimationIdle might fix the issue with this mod as well.

**Comment by ArranzCNL** [comment]
I've taken a look at this, it is just not compatible with however that mod operates.

Sorry.
