### ISSUE TITLE
Possible incompatibility with scale methods other than SetScale()

### ISSUE THREAD

**Issue by Sermitse** [ArranzCNL/ImprovedCameraSE#82]
We have a mod that alters the size of the player by adjusting the scale by using two possible methods (User decision):

-Bone Scale of Actors (**NPC Root [Root]**)
-Model Scale: Actor->Get3D(True/False)->model->local.scale

Source Code if you need to take a closer look:  https://github.com/QuantumEntangledAndy/GTS_Plugin/blob/camera_opt/src/scale/modscale.cpp

**The issue**: camera shifts above properly, but the body is being shifted forward/feels like only the body is scaled. So it ends up blocking the view and looking a bit weird.
The Video of it happening (A bit NSFW): 

https://user-images.githubusercontent.com/108320865/212457683-1ad5f000-c72d-4479-a00d-928e90dfceab.mp4

**Comment by ArranzCNL** [comment]
I see what is happening due to the body increasing in mass it needs pushing back based on the height from the camera.

Edit:
How does the first person arms look as I guess with those growing would ideally need to make them appear off screen?

**Comment by Sermitse** [comment]
That's how 1st and 3rd person arms look like, it further depends on how the body will rotate/zoom <details>(And it rotates a lot with the mouse, an option to make it rotate on WASD only would be nice. Something similar to TDM)</details> so it is a bit random.

I'll throw a bit of my opinion here - i think only the body should be fixed, feels like it will fix all other size-related issues

![SkyrimSE_jklax1ZmxW](https://user-images.githubusercontent.com/108320865/212480526-b495d722-6938-48ba-b37f-3e6077964426.jpg)
![SkyrimSE_MU5rOZHRJ4](https://user-images.githubusercontent.com/108320865/212480791-ff6a60a3-51dc-4a0c-abf2-1cdcfb12e1ee.jpg)

**Comment by ArranzCNL** [comment]
Right I've had a play around with player.setscale ranging from 0.2 (min) and 10 (max).
There are no issues with at least Vanilla/HIMBO/3BA on a complete naked body. (quite funny at 0.2 everything seems to wobble about alot more)

Can you confirm the same with your custom model using the above skyrim commands... just trying to rule out possible model issues.

**Comment by Sermitse** [comment]
Player.SetScale works fine, but using custom scaling methods such as altering Npc Root [Root] Scale / altering the Model Scale through the DLL - does not  (That's what i did on the video/screenshots)

If you will want to check how it behaves in-game yourself, you will have to install [Giantess Mod (.dll Version)](https://www.nexusmods.com/skyrimspecialedition/mods/37823) and quickly skip quests, skip skills and adjust your max size limit in extras. And then grow yourself with spells/mcm hotkeys/DLL hotkeys. All you need for it to work is Address Library and said dll version of the mod

**Comment by Sermitse** [comment]
> Right I've had a play around with player.setscale ranging from 0.2 (min) and 10 (max). There are no issues with at least Vanilla/HIMBO/3BA on a complete naked body. (quite funny at 0.2 everything seems to wobble about alot more)
> 
> Can you confirm the same with your custom model using the above skyrim commands... just trying to rule out possible model issues.

Edit: i tested Model Scale method from our mod (Scaling entire 3D model), and it works properly with your .dll without any issues.
 
So, only altering **NPC Root [Root]** bone breaks it like that so far, you can just alter it through script or something (if you want to test it without Giantess mod)

**Comment by ArranzCNL** [comment]
If you have 1 mode of scaling working which is far more universal what is the purpose of the other? I am trying to understand for both our sanities sake.

For now the universal mode (Model Scale) works not going to say never but maybe the other mode will be supported in the future.

**Comment by Sermitse** [comment]
> If you have 1 mode of scaling working which is far more universal what is the purpose of the other? I am trying to understand for both our sanities sake.
> 
> For now the universal mode (Model Scale) works not going to say never but maybe the other mode will be supported in the future.

The thing is - we have 2 modes of scaling because of the following issues: 
 - NPC Root [Root] Scale is working fine with everything except for body Overlays (tattoos, etc): it has issues when scaled (It is rendered incorrectly)
 - Model Scale is, conversely, working fine with everything since it scales entire model. However, it has random noticeable  resets to default scale when the actor is moving. So, player can notice sudden size shifts from x19.5 to 1.0 and then again to x19.5. Especially noticeable with HDT SMP physics.
 
 So, Root scale has overlay render issues, Mode Scale has random size resets issues (That's why there's a choice what to use). If it wouldn't have it, we would use Model Scale as a base for sure.

**Comment by ArranzCNL** [comment]
It sounds like altering the NPC Root doesn't cascade down the changes that it has been altered.

As for the model scale issue have you tested with no other mods loaded at all, to see if it is resetting? If it is still doing it you should be able to hook the call(s) to it and alter/replace them.

**Comment by Sermitse** [comment]
> It sounds like altering the NPC Root doesn't cascade down the changes that it has been altered.
> 
> As for the model scale issue have you tested with no other mods loaded at all, to see if it is resetting? If it is still doing it you should be able to hook the call(s) to it and alter/replace them.

It does it always, the Dev is planning to eventually fix it by hooking whatever is causing it, but it's probably not going to be easy to find it, after all he doesn't know what exactly to hook, at least currently.

For now we will stick with Npc Root [Root] scaling method, compatibility with your .dll would be nice, if you will decide to mess with it at least.

**Comment by ArranzCNL** [comment]
I think it might be coming from: SkyrimSE 1.5.97 - 0x14067C659 which is hard setting a scale to 1.0.

Signature if you want works on all SkyrimSE's well 1.5.97 - 1.6.659 (GOG) so you can obtain the other addresses.
`"E8 ?? ?? ?? FF 49 8B 06 BA 00 00 00 80 49 8B CE FF 50 50 49 8B 06"`

**Comment by Sermitse** [comment]
> I think it might be coming from: SkyrimSE 1.5.97 - 0x14067C659 which is hard setting a scale to 1.0.
> 
> Signature if you want works on all SkyrimSE's well 1.5.97 - 1.6.659 (GOG) so you can obtain the other addresses. `"E8 ?? ?? ?? FF 49 8B 06 BA 00 00 00 80 49 8B CE FF 50 50 49 8B 06"`

Thank you! 
Dll dev was trying to hook it lately, but game just crashes.
If possible, can you please give us a ready example of that hook? We would appreciate it a lot.
Here's how dev tried to hook it by using `common-lib` - logging stops at `Applying experimental hook: {:X}` (game crashes after that) : 
![chrome_w8Ix5bSpGL](https://user-images.githubusercontent.com/108320865/217224490-6235ff3c-5fdd-48ee-90c6-a66b1894b5a1.png)

(Link if you need to take a look for some reason: https://github.com/QuantumEntangledAndy/GTS_Plugin/blob/7ed4814a1cdfd9ed4b11e35377df2bfafc79d330/src/hooks/main.cpp)

**Comment by ArranzCNL** [comment]
Just quickly looking at this: (RelocationID's are based from 1.5.97)

38831 = 14067BFA0 (39861 for 1.6.353)
+0x6B9 = 14067C659 // This is the function I noticed calling 1.0 on the end.
0x6B9 is the offset from RelocationID (38831)
Note the offset on 1.6.318+ is 0x71F

36343 = 1405D61B0 (param_1 should be actor/player - param_2 should be the value of the scale size)
This is the actual function being called and sending 1.0 scale size too.
Above id in 1.6.353 is 37333

There is a way to dump the addresses from address library binaries into txt format (need to open in notepad++)
