### ISSUE TITLE
Light issues in first person

### ISSUE THREAD

**Issue by yytelliot** [ArranzCNL/ImprovedCameraSE#83]
There are some lighting bugs on skin in first person (see picture). It happens even when bEnableShadows is disabled.
![enb2023_1_14_22_52_47](https://user-images.githubusercontent.com/38177234/212478323-6665bb2d-8808-4da2-b698-79fb0cddc3a3.jpg)

**Comment by ArranzCNL** [comment]
bEnableShadows is placebo currently as it's not implemented.

However the lighting issues is possibly due to fNearDistance activating to allow seeing the body fully.

**Comment by yytelliot** [comment]
Changing fNearDistance to high or low values still does not seem to alleviate the issue. This problem was not present in improved camera 1 if that helps.

**Comment by ArranzCNL** [comment]
If it is still doing it with:
fNearDistanceFirstPerson=15.000000

I have no idea as there are too many mods that affect lighting and we don't touch lighting at all. We are aware of NearDistance screwing things up in outdoor areas which is mainly shadows going haywire. However if above is set to 15 and your still seeing it, another mod has to be the issue (might be multiple) regardless of IC version, even the very old beta1.

**Comment by yytelliot** [comment]
I have found out that this is caused by bloom effects from ENB, when bloom is turned off this issue disappears. Not sure why this is not present in IC 1.

**Comment by ArranzCNL** [comment]
Could be due to an enb update
