### ISSUE TITLE
Arms have no shadow in first person, but only with my weapons drawn.

### ISSUE THREAD

**Issue by DVR2703** [ArranzCNL/ImprovedCameraSE#85]
Hello, I've encountered an issue as mentioned above, I've read online that changing a line called "bUseThirdPersjavascript-event-stripped0" to 1 instead of 0 fixes this, but I can find no such line, and adding it does nothing, even when set to either 0 or 1. And an additional issue I've noticed is if I open a menu, the third-person arms appear (causing the arm shadows to appear as well) very briefly. Obviously these aren't game-breaking bugs, but they're annoying nonetheless, and I hope someone can help me fix them. If it's at all relevant, I'm on Skyrim AE version 1.6.353, and the corresponding version of SKSE, and below I've attached screenshots of the aforementioned issues in action.
(https://user-images.githubusercontent.com/122868515/212858072-5973af28-986f-4e90-8679-a575236e6bd3.png)
(https://user-images.githubusercontent.com/122868515/212858103-6be1e62f-86aa-410f-a514-a6f18c3fda6c.png)
(https://user-images.githubusercontent.com/122868515/212858168-383a5738-5cae-4d15-8626-f7a14b54286f.png)
EDIT: All that said, I hope I don't sound ungrateful or anything, Improved Camera will always be a part of my load order even with the aforementioned issues, you did an incredible job with the mod. :)

**Comment by noughtmare** [comment]
This is a known issue we want to fix before the 1.0 release, but it is really difficult.

> if I open a menu

Do you mean the inventory/magic/perk menu or the journal/stats/system menu (or something else)?

**Comment by DVR2703** [comment]
Inventory/Magic/Perk as seen in the screenshot, though that might be an issue on my end and not with Improved Camera, and it could actually probably be fixed by using that unpaused game menu mod. In any case, I'll be looking forward to the 1.0 release and I wish you luck in fixing the issue. :)

**Comment by noughtmare** [comment]
We have some checks in place that only hide the arms if you are in first person mode, but if you open that menu then the game is in a different mode. So I think we have just forgotten to check for that special condition.

**Comment by DVR2703** [comment]
Ah, that makes sense. Any advice on that "bUseThirdPersjavascript-event-stripped0" line? Like I said, I couldn't find it but that might be another issue on my end.

**Comment by noughtmare** [comment]
I think the `javascript-event-stripped0` part is some glitch from the place you got that, we have no option like that. We used to have `bUseThirdPersonArms`, but that is now called `bEnableArms` to use the third person arms even with weapons ready. That way the shadows usually work correctly, but your arms and weapons are then less easily visible. 

Even with that option it will still hide the arms while using a bow, so if you really want the shadows to always work correctly you have to set the `bEnableArmsBow=1` and `bEnableArmsAim=1` options too.

**Comment by DVR2703** [comment]
Much appreciated, and I'd use those options but sadly I also have Combat and Archery Gameplay Overhaul so I do need the first-person arms more than I need shadows for them. I think that's all I had, so thank you for the help and I wish you luck. :)
