### ISSUE TITLE
Status Update - PR5 and NG

### ISSUE THREAD

**Issue by ArranzCNL** [ArranzCNL/ImprovedCameraSE#86]
I know many of you have been requesting or inquiring about support for Skyrim 1.6.640 and GOG. Work shall begin on this from this upcoming week (more than likely from 25/01/23). How long will it take, how long is a piece of string? Joking aside hopefully 1-3wks - time dependant of course as it seems to be quite a major overhaul.

**What shall be contained in Preview Release 5:**
- ReShade is a hard requirement for the menu with certain mods detected. (Long story short - use a weird method and GameOverlay causes problems)
- Fixed FOV override not turning off as it should.
- Fixed scripted/animation flybacks, all of them! (Yes this was a B*tch!)
- Fixed camera staying in third person when it should be in first. (Campfire caused this, other mods as well)
- Added MediaKeys=1 to the ini file which allows media keys on your keyboard to work. **_Note: Can cause issues for non-us keyboards._**
- [Skyrim Upscaler](https://www.nexusmods.com/skyrimspecialedition/mods/80343) support.
- [HDT-SMP Force Fields](https://www.nexusmods.com/skyrimspecialedition/mods/79899) signature update.
- [Scrambled Bugs](https://www.nexusmods.com/skyrimspecialedition/mods/43532) signature update.
- Fixed misc menu issues. (which seem to only cause issues with myself!)
- Fixed first person positioning. (no more weird glitches when saving)
- Fixed first person headbob positioning to match normal.
- Fixed first person torch.
- Fixed DirectX11 present detection thanks to [PureDark](https://github.com/PureDark)
- Misc backend changes in preparation for NG update.
- Fixed double arm issue with Tween Menu.
- Fixed NearDistance override not turning off as it should.
- Fixed player placement in first person whilst sitting.
- Fixed camera positioning whilst sleeping.
- Fixed NearDistance so no more flickering shadows. **_Note: Detailed Shadows from ENBSeries (foilage/grass) are affected by this._**
- Fixed general ragdolls so your not propelled to timbuktu.
- Fixed death ragdolls so your not propelled to timbuktu.
- Reset State (from the menu) will now reset sit/sleep state flags which seem to be a common cause for the skating/sliding animation bug.
- Fixed force first person issues related to animations.
- Fixed model attachments to display in first person. (ie lantern)
- Added Quick Light Lighting under fixes for [Quick Light SE](https://www.nexusmods.com/skyrimspecialedition/mods/12633). **_Note: Activating will remove the lantern but the area will brighten up based on Quick Light settings._**
- Fixed mods/scripts which break the camera by incorrectly calling ForceFirstPerson().
- Updated sitting to use the other camera mode for more accurate positioning.
- Fixed torch to work again whilst sitting. (above probably broke it)
- Fixed getting on a horse in first person that switched to third person on some occasions.
- Fixed getting on a dragon in first person that switched to third person on some occasions.
- Fixed getting off a dragon in first person to remain in first person.

**Under dev:**
- POV toggle detection to block certain times entering first person fully, needs more work. This will solve game controller issues.
- Projectile misalignment, Physical seems fine aka arrows, magic and shouts need reviewing.
- bEnableShadows. The formidable missing arm/head shadow issue/hiding various states.
   Note: Some recent reversing has gone into this but not much, still want this fixed!

PR5 release date should be 27th - 29th Jan 2023 for Skyrim 1.5.97 and 1.6.353

To show <3 and support just report bugs etc as it will greatly help for NG release which will no doubt be released on [NexusMods](https://www.nexusmods.com/skyrimspecialedition).

**Shout out too:**
- [TwistedModding](https://github.com/TwistedModding) for tirelessly testing and helping me out personally with stupid modding questions!
- [Maxsu](https://github.com/max-su-2019) for a workable CommonlibSSE-NG to work from.
- [Capt. Panda](https://www.youtube.com/@CaptPanda) for an awesome showcase of [Improved Camera SE](https://www.youtube.com/watch?v=kqEZkN_KlR4) show your support and <3 for them!

**Upcoming Aspirations/Plans:**
- Full TDM support.
- Full Smoothcam support.
- Json support mainly for profiles.
- New UI system, possibly a separate mod.
- Total customisation over which animation can play out in first person.

One final note Fallout4 yes we hear you, at least NG needs to be done and dusted before any attempt is made to port and we know their is a major update coming this year at some point.

**Comment by lifeordeath2077** [comment]
> PR5 release date should be 27th - 29th Jan 2023 for Skyrim 1.5.97 and 1.6.353

So just to confirm this means that PR5 will not work on the 1.6.640 version of Skyrim? Regardless of that answer it's awesome to hear you're back on this mod, and that even if PR5 won't be for 1.6.640, that it will likely be compatible soon. Love this mod, an essential for me, have missed it dearly.

**Comment by ArranzCNL** [comment]
As explained in the opener nope. Pretty much need Improved Camera in a cleanless/buggy free state as much as possible before converting to the newer library hence PR5.

**Comment by BornToFrag** [comment]
any way we can test the beta of the mod?

**Comment by morgenrot68** [comment]
Too bad that the next update will still not be compatible with 1.6.640. Meanwhile almost all mods in my load order (>650 mods) are compatible with 1.6.640 (even DAR). The only major mods that are not yet compatible are ImprovedCameraSE, Fuz Ro Bork Text to Speech and .NET Script Framework. I'm waiting and hoping.

**Comment by Delfofthebla** [comment]
I'm pretty pumped. The flybacks kill me inside.

**Comment by ArranzCNL** [comment]
> I'm pretty pumped. The flybacks kill me inside.

That and the flickering shadows when the near distance was altered.

**Comment by ThesiiNCey** [comment]
any new about next update :/

**Comment by xirtz** [comment]
Can we expect to have a patch to work anytime soon on 1.6.629?

**Comment by somewhereovertherain** [comment]
https://github.com/ArranzCNL/ImprovedCameraSE/issues/42#issuecomment-1500776167

**Comment by somewhereovertherain** [comment]
> Can we expect to have a patch to work anytime soon on 1.6.629?

https://github.com/ArranzCNL/ImprovedCameraSE/issues/42#issuecomment-1500776167

**Comment by xirtz** [comment]
Alright, thanks. Good to know that at the very least the author is still active. Haven't tried this mod yet, but i am eager to see what it has to offer.

> > Can we expect to have a patch to work anytime soon on 1.6.629?
> 
> [#42 (comment)](https://github.com/ArranzCNL/ImprovedCameraSE/issues/42#issuecomment-1500776167)
