### ISSUE TITLE
Ragdoll effect makes player character flying much longer away than vanilla

### ISSUE THREAD

**Issue by pqow16** [ArranzCNL/ImprovedCameraSE#87]
Tested with unrenlenting force, and PC is flying fay away in FPP view.

**Comment by Glanzer-modder** [comment]
I've had the same experience when ragdolling after tripping on a rug in the "Rumpled Rugs" mod. In fact it sends me so far I sometimes pass through solid objects into areas I couldn't even get to normally. Also it almost kills me sometimes when I ragdoll. I didn't even think about what might be causing this until I read this issue. (Thanks pqow16)

**Comment by ArranzCNL** [comment]
Thanks for the bug report and confirmed, fix should be included in PR5's release.

Would be more comical if it sent you flying out of the door and it shut behind itself. :P I can imagine tripping on a rug and getting sent flying across the room is quite irriating! Made no sense when testing around Riverwood for myself I was sometimes sent flying into the river, must have thought I needed a wash.

**Comment by ArranzCNL** [comment]
Just to give a progress update on this... a fix shall be applied to the dev branch today or tomorrow either way can deem it as fixed for both ragdoll states, normal and death!

**Comment by ArranzCNL** [comment]
Fixed.

Note: [Poisebreaker](https://www.nexusmods.com/skyrimspecialedition/mods/74032) does break these Ragdoll effects from other mods, death works fine.
