### ISSUE TITLE
ctd

### ISSUE THREAD

**Issue by majorpluto** [ArranzCNL/ImprovedCameraSE#89]
https://pastebin.com/HJV0skHV

**Comment by majorpluto** [comment]
I think ultimate combats weapon swing effect may have had something to do with it.

**Comment by Glanzer-modder** [comment]
Looks more like a skeleton problem to me. You might want to check out XP32, I'm using just its skeleton meshes without any of the rest and it fixed some issues for me.

**Comment by majorpluto** [comment]
Turning off weapon swing effect from ultimate combat fixed the issue. That mod's weapon swing is buggy anyways so I don't care that much.

**Comment by ArranzCNL** [comment]
Can you repo the crash again with this:
[Crash Logger SSE AE VR - PDB support](https://www.nexusmods.com/skyrimspecialedition/mods/59818?tab=description)

I see he has a new one out which I must download, anyway it'll give more detailed crash report than .NetScriptFrameWork
