### ISSUE TITLE
Wearable lantrens 

### ISSUE THREAD

**Issue by majorpluto** [ArranzCNL/ImprovedCameraSE#90]
Wearable lanterns no longer work in first person. It worked fine in the previous version of improved camera.

**Comment by majorpluto** [comment]
Nvm turning on quicklight fix corrected the issue.

**Comment by ArranzCNL** [comment]
Quick question is Wearable Lanterns the more goto now as I noticed Quick Light SE is actually quite old?

**Comment by Glanzer-modder** [comment]
I think both will continue because Quick Light is simple (e.g. doesn't require lantern oil) whereas Wearable Lanterns is more of a survival/needs mod helper. I prefer Wearable Lanterns.

**Comment by ArranzCNL** [comment]
Ah ok
