### ISSUE TITLE
DLL Plugin has failed to load correctly?

### ISSUE THREAD

**Issue by krypto5863** [ArranzCNL/ImprovedCameraSE#91]
![image](https://user-images.githubusercontent.com/29824718/217060384-60901ea0-b47e-48fd-8097-3d889c471660.png)

Keep getting this with PR5. I'm on .353 so don't get why.

**Comment by ArranzCNL** [comment]
If your installing completely manually make sure you grab the files from the 1.6 folder. If installing via MO2 make sure 1.6.353 is selected.

**Comment by krypto5863** [comment]
I'm using MO2, 353 option was properly selected. It's the first thing I checked. Also pulled the 1.6 folder contents manually and threw them into to test, same result.

**Comment by ArranzCNL** [comment]
Make sure your SKSE is [v2.01.05](http://skse.silverlock.org/download/archive/skse64_2_01_05.7z)

Only other reason I can think of. Or unless there is a config failure it might do that, can check the log file for ImprovedCameraSE.log:

> C:\Users\USERNAME\Documents\My Games\Skyrim Special Edition\SKSE\ImprovedCameraSE.log

**Comment by krypto5863** [comment]
Ah, yeah no seems to have been the config, disabling my own config fixed it right up. Thanks, hadn't thought of that.
