### ISSUE TITLE
AE fishing incompatablity 

### ISSUE THREAD

**Issue by majorpluto** [ArranzCNL/ImprovedCameraSE#92]
Fishing with improved camera causes the player to get stuck in first person and unable to open 3rd person perspective.

**Comment by ArranzCNL** [comment]
Is that with Hotfix 1?

**Comment by Glanzer-modder** [comment]
fwiw I tested [Skyrim Fishing SE](https://www.nexusmods.com/skyrimspecialedition/mods/17774) and had no problems. I'm using Hotfix 1. Just letting you know.

**Comment by ArranzCNL** [comment]
Looking at fishing in 1.6.353 with and without IC installed, it always goes into First Person no matter what and you cannot enter third person looks like the POV switch is blocked.

It shouldn't have got stuck before Hotfix 1 was available as it is just in first person camera all the time and I see nothing untoward that would get it stuck.

If your still getting stuck then it has to be something else not Improved Camera.

**Comment by majorpluto** [comment]
Updating to hotfix 1 fixed this for me.

**Comment by ArranzCNL** [comment]
Awesome!
