### ISSUE TITLE
 Improved Camera SE 5 Pre-release not work properly with Quick Light SE!

### ISSUE THREAD

**Issue by Velezarius** [ArranzCNL/ImprovedCameraSE#93]
Improved Camera SE 1.0 Prerelease 5 does not work properly with Quick Light SE https://www.nexusmods.com/skyrimspecialedition/mods/12633?tab=description

**Comment by ArranzCNL** [comment]
bQuickLightLighting=0

Change above to 1 or enable it via the menu under fixes.
