### ISSUE TITLE
Random camera vertical shaking with Skyrim Outfit System SE Revived

### ISSUE THREAD

**Issue by pqow16** [ArranzCNL/ImprovedCameraSE#94]
It happens pretty randomly, so I don't really know how to reproduce it. When it happens, the issue persists even when my hands leave my mouse & keyboard. Also tested 3rd person view and vanilla 1st person view, and this issue didn't happen. 
I haven't removed other related mods (nemethis, xpmse, HDT stuffs...) to find the root cause, but decide to post here to see if others have the same issue.

**Comment by ArranzCNL** [comment]
I've never witnessed that at all yet and I actually been playing Skyrim completed the Dark Brotherhood,Thieves Guild so far.

**Comment by pqow16** [comment]
After a lot of trial and errors, I think the culprit is "Skyrim Outfit System SE Revived". It surprised me for I didn't think this mod would have problem with camera mods. The issue only happens when both mods are activated, but using one of the two mods don't have any problem.
Should I also report this issue to Skyrim Outfit System SE Revived?

**Comment by ArranzCNL** [comment]
I see a beta version got released yesterday, see if the issue persists with that one.

I find it abit odd how it would effect the camera though. When it occurs what happens if you go to third person then back to first does it still occur?

**Comment by pqow16** [comment]
The issue still persists with the beta version.

The second method can't fix the issue either.

**Comment by ArranzCNL** [comment]
You can see if it stops doing that if you disable the head, another thing you can try if you have the menu loaded is whilst in first person change the Y to see if you spot anything odd.

**Comment by pqow16** [comment]
Disabling head doesn't help. 

By "change the Y", I think you want me to test in a weird 3rd person mode. In that mode, I can see my character shaking with camera in the same time. I don't really find other odd things

I also discover a similar/identical sympton when switching gears with unpaused menu mod "Skyrim Souls RE - Updated", and the shaking chance is 100% in this case. Not sure if it is related, but may worth a look. 
Note: I also test the Skyrim Souls mod seperately, and it is unrelated to the random shake issue.
