### ISSUE TITLE
Script extender log reports incompatible plugins MO2

### ISSUE THREAD

**Issue by dangtruong1192** [ArranzCNL/ImprovedCameraSE#95]
You have one or more script extender plugins which failed to load!

 If you want this notification to go away, here are some steps you can take:
  • Look for updates to the mod or the specific plugin included in the mod.
  • Disable the mod containing the plugin.
  • Hide or delete the plugin from the mod.

To refresh the script extender logs, you will need to run the game and/or editor again!

The failed plugins are:
  • ImprovedCameraSE version 1 (ImprovedCameraSE.dll, Improved Camera SE) reported as incompatible during load.

I have SKSE for Skyrim 1.5.97 and I do not overwrite the INI file. Please show me how to fix it. Thank you very much.

**Comment by TwistedModding** [comment]
You are probably on the wrong version of skyrim for the version of improved camera you have

**Comment by dangtruong1192** [comment]
Thank you for your response. I managed to make it work. For anyone that has the same problem as mine. Simply, uninstall the old version and run the game, then install the new version.
