### ISSUE TITLE
third person arms first to third person indoors sticks MCO animations

### ISSUE THREAD

**Issue by therealnicoroshi** [ArranzCNL/ImprovedCameraSE#98]
game version 1.5.97
ADXP-MCO version 1.32
Improved camera (latest as of this writing)

How to reproduce issue:
Using third person arms, Third person Bow, Quick light fix
Weapons drawn in third person when in a cave switch to first person view. Wait 5 seconds. Switch back to third person.
MCO animations play but player does not move forward and hit boxes don't work until final strike of stringed animation.

To undo:
Switch back to first person (still interior space) wait 5 seconds. Switch back to third person view.
Acts like a toggle for me. This brings back step forward attack animations from MCO.

Everything works as intended with 3rd person arms unchecked. Also works as intended in exterior space.
Thank you for your continued work on this and for reading.

**Comment by ArranzCNL** [comment]
Must be just a weird conflict with ADXP whatever that is. Third person arms are problematic to begin with which I'd say more than likely 8/10 or even 9/10 don't even use.

**Comment by therealnicoroshi** [comment]
ADXP-MCO is
Modern combat overhaul created by Distar and available on SkyrimGuild. It is the successor to SkySA and many people use it.

Issue also happens with First person arms but requires a weapon change to trigger.
Only happens in interior cell.
Example of what i am experiencing:
Inside inn. Quick light on. weapons drawn. Go from third person view to first person. Switch weapon via hotkey. Return to third person view. Step forward animations now no longer step forward. 
Return to first person view. Switch weapons via hotkey. Return to third person.
Animations now advance like they should.
Watch video here of problem in action start 4:55 end 5:25
https://www.youtube.com/watch?v=OLYNeLZuK-4&t=4801s

The latest release is also giving me strange behavior with quick light and the quick light fix in interiors.
Example:
Quick light lantern using wide light on in third person.
Switch to first person.
Light is on but suddenly jumps way in front of my character.
Toggling back to third person puts the light where it should be.

Thanks again for your work and for reading, replying.
