### ISSUE TITLE
Signature with search_start=6caf64 not found.

### ISSUE THREAD

**Issue by monteverde7** [ArranzCNL/ImprovedCameraSE#99]
![image](https://user-images.githubusercontent.com/126293053/221296761-e9d4b7c5-fa93-44c7-9683-ad2c1b75e57e.png)

Modlist:

+BBLS_
-Player Locations_separator
+Immersive Armors 8.1 SSE Test
+Spellsword Moveset
+Dodge MCO-DXP
+VioLens - A Killmove Mod SE
+Unarmed Normal and Power For MCO
-No Spinning Death Animation
+Hand placed enemies
+Encounter Zones Unlocked SE
+ZAP
+More Blood
+One-Handed Normal And Power Sprint Attacks Animations
+One Click Power Attack
+No Recoil
+Enhanced Enemy AI
+Mortal Enemies SE
+Vanargand Animations - Crossbows
+Precision
+Valhalla Combat
+SCAR - Skyrim Combos AI Revolution
+Attack MCO-DXP
-Combat Mods_separator
+Serana's Hood Fix with Animation
+SDA Patch Hub SE
+Serana Dialogue Add-On SE
+Expressive Facial Animation - Male Edition
+Expressive Facial Animation - Female Edition
+Pantheon - Coralyn Bosmer Shaman - BHUNP
+ColdSun's Pantheon - Assets - BHUNP
+Heels Sound 1.5 SSE (Sound Fix)
+RS Children Overhaul
+SOS Full Vitruvia - Chest Hair
+Schlongs of Skyrim SE
+Highly Improved Male Body Overhaul
+BHUNP Egil's Demon Hunter
+Wet Function Redux SE
+Maxiteo - BHUNP Bodyslide Preset 2021
+Sawira body Preset bhunp
+BodySlide and Outfit Studio -
+Diamond Textures UNP
+CBPC - Physics with Collisions
+Faster HDT-SMP
+Baka Haeun UNP
-Body Mods_separator
+ElSopa HD Shields Part I
+ElSopa - Quivers Redone 4k SE
+Kvetchi Mercenary Set ESL
+Vanguard's Claymore Main File
+Immersive Weapons
+Lighter Color Daedric Dagger 2k
+Lore Weapon Expansion
+Zim's Immersive Artifacts
+Immersive Equipment Displays for 1.5.39 - 1.6.353
+Simple Dual Sheath for 1.5.39 - 1.6.353
+ElSopa - Iron Weapons Redone 2k
+ElSopa Glorious HD Amulets 1k Max Performance
+Believable weapons
+LeanWolf's Better-Shaped Weapons - All in One Installer
-Weapons Armor_separator
+Reverb Interior Sounds Expansion
+Regional Sounds Expansion (2.0.0)
+Audio Overhaul Skyrim - Immersive Sounds Compendium Integration (1.1.0)
+Sound Record Distributor
+Audio Overhaul for Skyrim (4.0.0)
+Immersive Sounds - Compendium
-Sound_separator
+Parallax with shadows
+Northern Ice
+JS Dwemer Control Cube SE - 2k Textures
+aMidianBorn Book of Silence SE
+ElSopa - Potions Redone 4k
+Better Chest 4K Optimised SSE Version
+Storm Lightning for SSE and VR (Minty Lightning 2019)
+TB's Better Lanterns
+TB's HD Lanterns 4K Optimised SSE Version
+Lanterns Of Skyrim II
+City Trees - Whiterun Lanterns
+Ores Veins and Ingots - ENB Complex Material 2K
+Medieval Spirits
+Ancient Pottery
+Rally's Crates
+Skyrim 3D Windmill
+ENB Helper SE 1.5 for SSE 1.5.97
+River Stone 2k Parallax BC7
+Particle Patch for ENB
+Vivid Landscapes - Complex Parallax Occlusion Woods 2k
+Windy Grass - Multiplier 7
+Glorious Doors of Skyrim (GDOS)
+Cathedral - 3D Tundra Cotton
+Cathedral - 3D Snow Berries - Green
+Cathedral - 3D Mountain Flowers
+Woody's 3D Ground Cover Plants - Yellow Archangel
+JS Emissive Eyes SE
+JS Purses and Septims SE
+2k Textures
+TB's 8K Tower 2K Performance Version
+Volcanic Tundra 2k
+TB's 8K Immersive Mines 2K Performance SSE Variant
+TB's Immersive Caves 2K Performance Variant
+Smoother Skies
+Night Skies - Vanilla Blue (8K) - CP
+Landscape Fixes For Grass Mods
+High Poly Project
+Deadly Spells Impacts Transparency Fix
+Deadly Spell Impacts
+Rudy HQ - Falling Leaves and Needles for ENB SE
-Better Dynamic Majestic Mountains
+Better Dynamic Snow SE
+Vivid Landscapes - Complex Parallax Snow 1k
+Auto Parallax
+Skyrim 3D Rocks
+Skyrim 3D Landscapes
+SRP Dungeons 2K
-Northern Marsh Bridges SE
+Ryn's Farms
+Ryn's Bleak Falls Tower
+Ryns Bleakwind Basin USSEP fix
+Ryn's Bleakwind Basin
+Ryn's Goldenglow Estate
+Ryn's Halted Stream Camp
+Ryn's Saarthal
+Ryn's Karthspire
+Ryn's Mistwatch Folly
+Ryn's Standing Stones
+JK's Castle Dour
+JK's Whiterun Outskirts
+JK's Sinderion's Field Laboratory
+JK's Septimus Signus's Outpost
+JK's Sky Haven Temple
+JK's High Hrothgar
+JK's Jorrvaskr
+JK's Haelga's Bunkhouse
+JK's Temple of Talos
+JK's Temple of the Divines
+JK's Temple of Kynareth
+JK's Temple of Dibella
+JK's Riverwood Trader
+JK's Understone Keep
+JK's The Hag's Cure
+JK's Arnleif and Sons Trading Company
+JK's Silver-Blood Inn
+JK's The Temple of Mara
+JK's Mistveil Keep
+JK's The Ragged Flagon
+JK's The Pawned Prawn
+JK's Elgrims Elixirs
+JK's The Bee and Barb
+JK's Palace of the Kings
+JK's New Gnisis Cornerclub
+JK's Sadris Used Wares
+JK's White Phial
+JK's Candlehearth Hall
+JK's Blue Palace
+JK's Bits and Pieces
+Jk's Angeline's Aromatics
+Jk's The Winking Skeever
+JK's Sleeping Giant Inn
+JK's Dragonsreach
+JK's The Bannered Mare
+JK's Skyrim - Towns
+JK's Skyrim No Lights Patch
+JK's Skyrim all in one
+JK's Interiors Patch Collection
+Water for ENB
+Nordic Northern Roads 2K
+Northern Roads Patch Collection
+Northern Roads
+Origins Of Forest - 3D Forest Grass
+Folkvangr - Grass and Landscape Overhaul
+2K Ulvenwald 3.1 - Forest Overhaul
+Blended Roads
-Unofficial eFPS Patches
+eFPS - Exterior FPS boost
-DynDOLOD DLL SE - SKSE64 Plugin - Skyrim Special Edition 1.6.40
-DynDOLOD DLL SE - Scripts
-DynDOLOD Resources SE
+Embers XD
+EVLaS
+ENB Light
+Lux - Via
+Lux Orbis
-Lux - Updated SMIM meshes
+Lux
+Smim - Quality Addon
+Majestic Mountains Lightside
-Majestic Mountains Main
+Skyrim Landscape and Water Fixes
+Static Mesh Improvement Mod
+Skyland AIO
-GraphicsPhysics_separator
+MorrowLoot Ultimate 2.0d
+Disable Turn Animation SE I AE
+OPrivacy
+Naughty Voices
+Moon Lovemaking Compendium
+OpenSex Addon Hub
+OpenSex
+OStim
+OSA
+Improved Camera SE - OStim NG Configuration File
+Improved Camera SE
+Vanargand Animations - Sneak Idle Walk and Run
+Vanargand Animations - Archery
+Goetia Animations - Conditional Shouts
+Payload Interpreter
+Animation Motion Revolution
+JK Maleficus Transversal patch
+EVG Animation Variance
+EVGAT - Caine's Roof Access for Deadly Shadows for JK's Skyrim
+Maleficus' Traversal (EVGAT)
+EVG Animated Traversal - Patch Collection
+EVGAT Skyrim Integration Patch
+EVG Animated Traversal
+Read the Room
+Gesture Animation Remix (DAR) - main archive
+DynamicAnimationReplacer v1.1.0 for SkyrimSE
+Nemesis Unlimited Behavior Engine
+XP32 Maximum Skeleton Special Extended
+The Innocence Lost - Quest Expansion
+Better Jumping SE
+Dynamic Weather and Time Based Detection
+Detection Meter-v0.17-SE
+Andromeda 1.1.2
+Summermyst
+Infinite Stamina Out of Combat
+Better Stealth AI for Followers
+Book Of Shadows
+Alternate Start
+Legacy of the Dragonborn Patches (Official)
+Immersive World Encounters SE
+Deadly Shadows for JK's Skyrim
+AI Overhaul SSE
+Imperious 7.28.0
+Headhunter - Bounties Redone
+Mysticism - Ordinator Patch
+Apocalypse - Ordinator Compatibility Patch WHY DO I HAVE TO CHANGE THE NAME
+Apocalypse
+Mysticism - A Magic Overhaul
+Ordinator 9.31.0
+Arena - An Encounter Zone Overhaul
+Skyshards - ENB Addon
+Skyshards
+Locked Chests Have Keys
+Civil War Lines Expansion
+Forsworn and Thalmor Lines Expansion
+Legacy of the Dragonborn
+Bandit Lines Expansion
+SmoothCam - Soft Preset
+SmoothCam
+True Directional Movement
+Complete Alchemy & Cooking Overhaul
+At Your Own Pace - Skyrim Unbound
+Skyrim Unbound Reborn
-Gameplay Changes_separator
+Immersive HUD Patch
+No FNIS.esp
+SkyUI SE - Flashing Savegames Fix
+AddItemMenuSE_114_SKSE2019
+Immersive HUD - iHUD
+JContainers SE
+NORDIC UI - Interface Overhaul
+SkyHUD
+UIExtensions
+(Skyrim Special Edition) SSE Fixes v3 for SSE 1.5.97
+Papyrus Tweaks 4.0
+Spell Perk Item Distributor
+MCM Helper SE
+Bug Fixes SSE (Special Edition)
+SkyUI_5_2_SE
+Skyrim Priority SE AE
+SSE Display Tweaks
+RaceMenu Special Edition
+powerofthree's Tweaks
+(Part 1) SSE Engine Fixes for 1.5.39 - 1.5.97
+All in one
+Unofficial Skyrim Special Edition Patch
-Game Fixes UI_separator
*DLC: Dawnguard
*DLC: Dragonborn
*DLC: HearthFires
*Unmanaged: Cathedral Weathers

**Comment by ArranzCNL** [comment]
You've loaded the incorrect dll, that signature only occurs when attempting to load the 1.6.353 binary instead of the 1.5.97.
